/**
 * This class is generated by jOOQ
 */
package org.jooq.test.hsqldb.generatedclasses.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.test.hsqldb.generatedclasses.Public;


/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class F2515_ extends AbstractRoutine<java.lang.Integer> {

	private static final long serialVersionUID = 1292431970;

	/**
	 * The parameter <code>PUBLIC.F2515_.RETURN_VALUE</code>.
	 */
	public static final Parameter<java.lang.Integer> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>PUBLIC.F2515_.A_A</code>.
	 */
	public static final Parameter<java.lang.Integer> A_A = createParameter("A_A", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>PUBLIC.F2515_.A_A_</code>.
	 */
	public static final Parameter<java.lang.Integer> A_A_ = createParameter("A_A_", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * Create a new routine call instance
	 */
	public F2515_() {
		super("F2515_", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER);

		setReturnParameter(RETURN_VALUE);
		addInParameter(A_A);
		addInParameter(A_A_);
	}

	/**
	 * Set the <code>A_A</code> parameter IN value to the routine
	 */
	public void setAA(java.lang.Integer value) {
		setValue(A_A, value);
	}

	/**
	 * Set the <code>A_A</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setAA(Field<java.lang.Integer> field) {
		setField(A_A, field);
	}

	/**
	 * Set the <code>A_A_</code> parameter IN value to the routine
	 */
	public void setAA_(java.lang.Integer value) {
		setValue(A_A_, value);
	}

	/**
	 * Set the <code>A_A_</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setAA_(Field<java.lang.Integer> field) {
		setField(A_A_, field);
	}
}
