/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle.generatedclasses.usr_2522_a;


import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.test.oracle.generatedclasses.usr_2522_a.routines.F_2522;
import org.jooq.test.oracle.generatedclasses.usr_2522_a.udt.records.U_2522Record;


/**
 * Convenience access to all stored procedures and functions in USR_2522_A
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

	/**
	 * Call <code>USR_2522_A.F_2522</code>
	 */
	public static U_2522Record f_2522(Configuration configuration) {
		F_2522 f = new F_2522();

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>USR_2522_A.F_2522</code> as a field
	 */
	public static Field<U_2522Record> f_2522() {
		F_2522 f = new F_2522();

		return f.asField();
	}
}
