/**
 * Copyright (c) 2009-2015, Data Geekery GmbH (http://www.datageekery.com)
 * All rights reserved.
 * 
 * This work is dual-licensed
 * - under the Apache Software License 2.0 (the "ASL")
 * - under the jOOQ License and Maintenance Agreement (the "jOOQ License")
 * =============================================================================
 * You may choose which license applies to you:
 * 
 * - If you're using this work with Open Source databases, you may choose
 *   either ASL or jOOQ License.
 * - If you're using this work with at least one commercial database, you must
 *   choose jOOQ License
 * 
 * For more information, please visit http://www.jooq.org/licenses
 * 
 * Apache Software License 2.0:
 * -----------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *  http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * jOOQ License and Maintenance Agreement:
 * -----------------------------------------------------------------------------
 * Data Geekery grants the Customer the non-exclusive, timely limited and
 * non-transferable license to install and use the Software under the terms of
 * the jOOQ License and Maintenance Agreement.
 * 
 * This library is distributed with a LIMITED WARRANTY. See the jOOQ License
 * and Maintenance Agreement for more details: http://www.jooq.org/licensing
 */
package org.jooq.xtend;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IntegerRange;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.jooq.Constants;
import org.jooq.xtend.Generators;

@SuppressWarnings("all")
public class DSLContext extends Generators {
  public static void main(final String[] args) {
    final DSLContext ctx = new DSLContext();
    ctx.generateNewRecord();
    ctx.generateNewResult();
    ctx.generateSelect();
    ctx.generateSelectDistinct();
    ctx.generateInsert();
    ctx.generateMerge();
  }
  
  public void generateNewRecord() {
    final StringBuilder outImpl = new StringBuilder();
    final StringBuilder outAPI = new StringBuilder();
    IntegerRange _upTo = new IntegerRange(1, Constants.MAX_ROW_DEGREE);
    for (final Integer degree : _upTo) {
      {
        String fieldOrRow = ("Row" + degree);
        if (((degree).intValue() == 1)) {
          fieldOrRow = "Field";
        }
        StringConcatenation _builder = new StringConcatenation();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("/**");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* Create a new empty {@link Record}.");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <p>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* The resulting record is attached to this {@link Configuration} by");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* default. Use {@link Settings#isAttachRecords()} to override this");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* behaviour.");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* @return The new record");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*/");
        _builder.newLine();
        _builder.append("    ");
        CharSequence _generatedMethod = this.generatedMethod();
        _builder.append(_generatedMethod, "    ");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("<");
        String _TN = this.TN((degree).intValue());
        _builder.append(_TN, "    ");
        _builder.append("> Record");
        CharSequence _recTypeSuffix = this.recTypeSuffix((degree).intValue());
        _builder.append(_recTypeSuffix, "    ");
        _builder.append(" newRecord(");
        String _Field_TN_fieldn = this.Field_TN_fieldn((degree).intValue());
        _builder.append(_Field_TN_fieldn, "    ");
        _builder.append(");");
        _builder.newLineIfNotEmpty();
        outAPI.append(_builder);
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.newLine();
        _builder_1.append("    ");
        CharSequence _generatedMethod_1 = this.generatedMethod();
        _builder_1.append(_generatedMethod_1, "    ");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    ");
        _builder_1.append("@Override");
        _builder_1.newLine();
        _builder_1.append("    ");
        _builder_1.append("public <");
        String _TN_1 = this.TN((degree).intValue());
        _builder_1.append(_TN_1, "    ");
        _builder_1.append("> Record");
        CharSequence _recTypeSuffix_1 = this.recTypeSuffix((degree).intValue());
        _builder_1.append(_recTypeSuffix_1, "    ");
        _builder_1.append(" newRecord(");
        String _Field_TN_fieldn_1 = this.Field_TN_fieldn((degree).intValue());
        _builder_1.append(_Field_TN_fieldn_1, "    ");
        _builder_1.append(") {");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("        ");
        _builder_1.append("return (Record");
        CharSequence _recTypeSuffixRaw = this.recTypeSuffixRaw((degree).intValue());
        _builder_1.append(_recTypeSuffixRaw, "        ");
        _builder_1.append(") newRecord(new Field[] { ");
        String _fieldn = this.fieldn((degree).intValue());
        _builder_1.append(_fieldn, "        ");
        _builder_1.append(" });");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    ");
        _builder_1.append("}");
        _builder_1.newLine();
        outImpl.append(_builder_1);
      }
    }
    this.insert("org.jooq.DSLContext", outAPI, "newRecord");
    this.insert("org.jooq.impl.DefaultDSLContext", outImpl, "newRecord");
  }
  
  public void generateNewResult() {
    final StringBuilder outImpl = new StringBuilder();
    final StringBuilder outAPI = new StringBuilder();
    IntegerRange _upTo = new IntegerRange(1, Constants.MAX_ROW_DEGREE);
    for (final Integer degree : _upTo) {
      {
        String fieldOrRow = ("Row" + degree);
        if (((degree).intValue() == 1)) {
          fieldOrRow = "Field";
        }
        StringConcatenation _builder = new StringConcatenation();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("/**");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* Create a new empty {@link Result}.");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <p>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* The resulting result is attached to this {@link Configuration} by");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* default. Use {@link Settings#isAttachRecords()} to override this");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* behaviour.");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* @return The new result");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*/");
        _builder.newLine();
        _builder.append("    ");
        CharSequence _generatedMethod = this.generatedMethod();
        _builder.append(_generatedMethod, "    ");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("<");
        String _TN = this.TN((degree).intValue());
        _builder.append(_TN, "    ");
        _builder.append("> Result<Record");
        CharSequence _recTypeSuffix = this.recTypeSuffix((degree).intValue());
        _builder.append(_recTypeSuffix, "    ");
        _builder.append("> newResult(");
        String _Field_TN_fieldn = this.Field_TN_fieldn((degree).intValue());
        _builder.append(_Field_TN_fieldn, "    ");
        _builder.append(");");
        _builder.newLineIfNotEmpty();
        outAPI.append(_builder);
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.newLine();
        _builder_1.append("    ");
        CharSequence _generatedMethod_1 = this.generatedMethod();
        _builder_1.append(_generatedMethod_1, "    ");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    ");
        _builder_1.append("@Override");
        _builder_1.newLine();
        _builder_1.append("    ");
        _builder_1.append("public <");
        String _TN_1 = this.TN((degree).intValue());
        _builder_1.append(_TN_1, "    ");
        _builder_1.append("> Result<Record");
        CharSequence _recTypeSuffix_1 = this.recTypeSuffix((degree).intValue());
        _builder_1.append(_recTypeSuffix_1, "    ");
        _builder_1.append("> newResult(");
        String _Field_TN_fieldn_1 = this.Field_TN_fieldn((degree).intValue());
        _builder_1.append(_Field_TN_fieldn_1, "    ");
        _builder_1.append(") {");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("        ");
        _builder_1.append("return (Result) newResult(new Field[] { ");
        String _fieldn = this.fieldn((degree).intValue());
        _builder_1.append(_fieldn, "        ");
        _builder_1.append(" });");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    ");
        _builder_1.append("}");
        _builder_1.newLine();
        outImpl.append(_builder_1);
      }
    }
    this.insert("org.jooq.DSLContext", outAPI, "newResult");
    this.insert("org.jooq.impl.DefaultDSLContext", outImpl, "newResult");
  }
  
  public void generateSelect() {
    final StringBuilder outDSL = new StringBuilder();
    final StringBuilder outImpl = new StringBuilder();
    final StringBuilder outAPI = new StringBuilder();
    IntegerRange _upTo = new IntegerRange(1, Constants.MAX_ROW_DEGREE);
    for (final Integer degree : _upTo) {
      {
        String fieldOrRow = ("Row" + degree);
        if (((degree).intValue() == 1)) {
          fieldOrRow = "Field";
        }
        StringConcatenation _builder = new StringConcatenation();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("/**");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* Create a new DSL select statement.");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <p>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* This is the same as {@link #select(Field...)}, except that it");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* declares additional record-level typesafety, which is needed by");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* {@link ");
        _builder.append(fieldOrRow, "     ");
        _builder.append("#in(Select)}, {@link ");
        _builder.append(fieldOrRow, "     ");
        _builder.append("#equal(Select)} and other predicate");
        _builder.newLineIfNotEmpty();
        _builder.append("     ");
        _builder.append("* building methods taking subselect arguments.");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <p>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* This creates an attached, renderable and executable <code>SELECT</code>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* statement from this {@link DSLContext}. If you don\'t need to render or");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* execute this <code>SELECT</code> statement (e.g. because you want to");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* create a subselect), consider using the static");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* {@link DSL#select(");
        {
          IntegerRange _upTo_1 = new IntegerRange(1, (degree).intValue());
          boolean _hasElements = false;
          for(final Integer d : _upTo_1) {
            if (!_hasElements) {
              _hasElements = true;
            } else {
              _builder.appendImmediate(", ", "     ");
            }
            _builder.append("SelectField");
          }
        }
        _builder.append(")} instead.");
        _builder.newLineIfNotEmpty();
        _builder.append("     ");
        _builder.append("* <p>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* Example: <code><pre>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* using(configuration)");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*       .select(");
        String _field1_field2_fieldn = this.field1_field2_fieldn((degree).intValue());
        _builder.append(_field1_field2_fieldn, "     ");
        _builder.append(")");
        _builder.newLineIfNotEmpty();
        _builder.append("     ");
        _builder.append("*       .from(table1)");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*       .join(table2).on(field1.equal(field2))");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*       .where(field1.greaterThan(100))");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*       .orderBy(field2);");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* </pre></code>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* @see DSL#selectDistinct(SelectField...)");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* @see #selectDistinct(SelectField...)");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*/");
        _builder.newLine();
        _builder.append("    ");
        CharSequence _generatedMethod = this.generatedMethod();
        _builder.append(_generatedMethod, "    ");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("@Support");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<");
        String _TN = this.TN((degree).intValue());
        _builder.append(_TN, "    ");
        _builder.append("> SelectSelectStep<Record");
        _builder.append(degree, "    ");
        _builder.append("<");
        String _TN_1 = this.TN((degree).intValue());
        _builder.append(_TN_1, "    ");
        _builder.append(">> select(");
        String _SelectField_TN_fieldn = this.SelectField_TN_fieldn((degree).intValue());
        _builder.append(_SelectField_TN_fieldn, "    ");
        _builder.append(");");
        _builder.newLineIfNotEmpty();
        outAPI.append(_builder);
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.newLine();
        _builder_1.append("    ");
        _builder_1.append("/**");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* Create a new DSL subselect statement.");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <p>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* This is the same as {@link #select(Field...)}, except that it declares");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* additional record-level typesafety, which is needed by");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* {@link ");
        _builder_1.append(fieldOrRow, "     ");
        _builder_1.append("#in(Select)}, {@link ");
        _builder_1.append(fieldOrRow, "     ");
        _builder_1.append("#equal(Select)} and other predicate");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("     ");
        _builder_1.append("* building methods taking subselect arguments.");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <p>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* Unlike {@link Select} factory methods in the {@link DSLContext} API, this");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* creates an unattached, and thus not directly renderable or executable");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <code>SELECT</code> statement. You can use this statement in two ways:");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <ul>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <li>As a subselect within another select</li>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <li>As a statement, after attaching it using");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* {@link Select#attach(org.jooq.Configuration)}</li>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* </ul>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <p>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* Example: <code><pre>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* import static org.jooq.impl.DSL.*;");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* // [...]");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* select(");
        String _field1_field2_fieldn_1 = this.field1_field2_fieldn((degree).intValue());
        _builder_1.append(_field1_field2_fieldn_1, "     ");
        _builder_1.append(")");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("     ");
        _builder_1.append("*  .from(table1)");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*  .join(table2).on(field1.equal(field2))");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*  .where(field1.greaterThan(100))");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*  .orderBy(field2);");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* </pre></code>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* @see DSLContext#select(SelectField...)");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* @see #select(SelectField...)");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*/");
        _builder_1.newLine();
        _builder_1.append("    ");
        CharSequence _generatedMethod_1 = this.generatedMethod();
        _builder_1.append(_generatedMethod_1, "    ");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    ");
        _builder_1.append("@Support");
        _builder_1.newLine();
        _builder_1.append("    ");
        _builder_1.append("public static <");
        String _TN_2 = this.TN((degree).intValue());
        _builder_1.append(_TN_2, "    ");
        _builder_1.append("> SelectSelectStep<Record");
        _builder_1.append(degree, "    ");
        _builder_1.append("<");
        String _TN_3 = this.TN((degree).intValue());
        _builder_1.append(_TN_3, "    ");
        _builder_1.append(">> select(");
        String _SelectField_TN_fieldn_1 = this.SelectField_TN_fieldn((degree).intValue());
        _builder_1.append(_SelectField_TN_fieldn_1, "    ");
        _builder_1.append(") {");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("        ");
        _builder_1.append("return (SelectSelectStep) select(new SelectField[] { ");
        String _fieldn = this.fieldn((degree).intValue());
        _builder_1.append(_fieldn, "        ");
        _builder_1.append(" });");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    ");
        _builder_1.append("}");
        _builder_1.newLine();
        outDSL.append(_builder_1);
        StringConcatenation _builder_2 = new StringConcatenation();
        _builder_2.newLine();
        _builder_2.append("    ");
        CharSequence _generatedMethod_2 = this.generatedMethod();
        _builder_2.append(_generatedMethod_2, "    ");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("    ");
        _builder_2.append("@Override");
        _builder_2.newLine();
        _builder_2.append("    ");
        _builder_2.append("public <");
        String _TN_4 = this.TN((degree).intValue());
        _builder_2.append(_TN_4, "    ");
        _builder_2.append("> SelectSelectStep<Record");
        _builder_2.append(degree, "    ");
        _builder_2.append("<");
        String _TN_5 = this.TN((degree).intValue());
        _builder_2.append(_TN_5, "    ");
        _builder_2.append(">> select(");
        String _SelectField_TN_fieldn_2 = this.SelectField_TN_fieldn((degree).intValue());
        _builder_2.append(_SelectField_TN_fieldn_2, "    ");
        _builder_2.append(") {");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("        ");
        _builder_2.append("return (SelectSelectStep) select(new SelectField[] { ");
        String _fieldn_1 = this.fieldn((degree).intValue());
        _builder_2.append(_fieldn_1, "        ");
        _builder_2.append(" });");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("    ");
        _builder_2.append("}");
        _builder_2.newLine();
        outImpl.append(_builder_2);
      }
    }
    this.insert("org.jooq.DSLContext", outAPI, "select");
    this.insert("org.jooq.impl.DefaultDSLContext", outImpl, "select");
    this.insert("org.jooq.impl.DSL", outDSL, "select");
  }
  
  public void generateSelectDistinct() {
    final StringBuilder outDSL = new StringBuilder();
    final StringBuilder outImpl = new StringBuilder();
    final StringBuilder outAPI = new StringBuilder();
    IntegerRange _upTo = new IntegerRange(1, Constants.MAX_ROW_DEGREE);
    for (final Integer degree : _upTo) {
      {
        String fieldOrRow = ("Row" + degree);
        if (((degree).intValue() == 1)) {
          fieldOrRow = "Field";
        }
        StringConcatenation _builder = new StringConcatenation();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("/**");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* Create a new DSL select statement.");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <p>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* This is the same as {@link #selectDistinct(Field...)}, except that it");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* declares additional record-level typesafety, which is needed by");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* {@link ");
        _builder.append(fieldOrRow, "     ");
        _builder.append("#in(Select)}, {@link ");
        _builder.append(fieldOrRow, "     ");
        _builder.append("#equal(Select)} and other predicate");
        _builder.newLineIfNotEmpty();
        _builder.append("     ");
        _builder.append("* building methods taking subselect arguments.");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <p>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* This creates an attached, renderable and executable <code>SELECT</code>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* statement from this {@link DSLContext}. If you don\'t need to render or");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* execute this <code>SELECT</code> statement (e.g. because you want to");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* create a subselect), consider using the static");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* {@link DSL#selectDistinct(");
        {
          IntegerRange _upTo_1 = new IntegerRange(1, (degree).intValue());
          boolean _hasElements = false;
          for(final Integer d : _upTo_1) {
            if (!_hasElements) {
              _hasElements = true;
            } else {
              _builder.appendImmediate(", ", "     ");
            }
            _builder.append("SelectField");
          }
        }
        _builder.append(")} instead.");
        _builder.newLineIfNotEmpty();
        _builder.append("     ");
        _builder.append("* <p>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* Example: <code><pre>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* using(configuration)");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*       .selectDistinct(");
        String _field1_field2_fieldn = this.field1_field2_fieldn((degree).intValue());
        _builder.append(_field1_field2_fieldn, "     ");
        _builder.append(")");
        _builder.newLineIfNotEmpty();
        _builder.append("     ");
        _builder.append("*       .from(table1)");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*       .join(table2).on(field1.equal(field2))");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*       .where(field1.greaterThan(100))");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*       .orderBy(field2);");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* </pre></code>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* @see DSL#selectDistinct(SelectField...)");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* @see #selectDistinct(SelectField...)");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*/");
        _builder.newLine();
        _builder.append("    ");
        CharSequence _generatedMethod = this.generatedMethod();
        _builder.append(_generatedMethod, "    ");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("@Support");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<");
        String _TN = this.TN((degree).intValue());
        _builder.append(_TN, "    ");
        _builder.append("> SelectSelectStep<Record");
        _builder.append(degree, "    ");
        _builder.append("<");
        String _TN_1 = this.TN((degree).intValue());
        _builder.append(_TN_1, "    ");
        _builder.append(">> selectDistinct(");
        String _SelectField_TN_fieldn = this.SelectField_TN_fieldn((degree).intValue());
        _builder.append(_SelectField_TN_fieldn, "    ");
        _builder.append(");");
        _builder.newLineIfNotEmpty();
        outAPI.append(_builder);
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.newLine();
        _builder_1.append("    ");
        _builder_1.append("/**");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* Create a new DSL subselect statement.");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <p>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* This is the same as {@link #selectDistinct(Field...)}, except that it");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* declares additional record-level typesafety, which is needed by");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* {@link ");
        _builder_1.append(fieldOrRow, "     ");
        _builder_1.append("#in(Select)}, {@link ");
        _builder_1.append(fieldOrRow, "     ");
        _builder_1.append("#equal(Select)} and other predicate");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("     ");
        _builder_1.append("* building methods taking subselect arguments.");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <p>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* Unlike {@link Select} factory methods in the {@link DSLContext} API, this");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* creates an unattached, and thus not directly renderable or executable");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <code>SELECT</code> statement. You can use this statement in two ways:");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <ul>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <li>As a subselect within another select</li>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <li>As a statement, after attaching it using");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* {@link Select#attach(org.jooq.Configuration)}</li>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* </ul>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <p>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* Example: <code><pre>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* import static org.jooq.impl.DSL.*;");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* // [...]");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* selectDistinct(");
        String _field1_field2_fieldn_1 = this.field1_field2_fieldn((degree).intValue());
        _builder_1.append(_field1_field2_fieldn_1, "     ");
        _builder_1.append(")");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("     ");
        _builder_1.append("*  .from(table1)");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*  .join(table2).on(field1.equal(field2))");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*  .where(field1.greaterThan(100))");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*  .orderBy(field2);");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* </pre></code>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* @see DSLContext#selectDistinct(SelectField...)");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* @see #selectDistinct(SelectField...)");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*/");
        _builder_1.newLine();
        _builder_1.append("    ");
        CharSequence _generatedMethod_1 = this.generatedMethod();
        _builder_1.append(_generatedMethod_1, "    ");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    ");
        _builder_1.append("@Support");
        _builder_1.newLine();
        _builder_1.append("    ");
        _builder_1.append("public static <");
        String _TN_2 = this.TN((degree).intValue());
        _builder_1.append(_TN_2, "    ");
        _builder_1.append("> SelectSelectStep<Record");
        _builder_1.append(degree, "    ");
        _builder_1.append("<");
        String _TN_3 = this.TN((degree).intValue());
        _builder_1.append(_TN_3, "    ");
        _builder_1.append(">> selectDistinct(");
        String _SelectField_TN_fieldn_1 = this.SelectField_TN_fieldn((degree).intValue());
        _builder_1.append(_SelectField_TN_fieldn_1, "    ");
        _builder_1.append(") {");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("        ");
        _builder_1.append("return (SelectSelectStep) selectDistinct(new SelectField[] { ");
        String _fieldn = this.fieldn((degree).intValue());
        _builder_1.append(_fieldn, "        ");
        _builder_1.append(" });");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    ");
        _builder_1.append("}");
        _builder_1.newLine();
        outDSL.append(_builder_1);
        StringConcatenation _builder_2 = new StringConcatenation();
        _builder_2.newLine();
        _builder_2.append("    ");
        CharSequence _generatedMethod_2 = this.generatedMethod();
        _builder_2.append(_generatedMethod_2, "    ");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("    ");
        _builder_2.append("@Override");
        _builder_2.newLine();
        _builder_2.append("    ");
        _builder_2.append("public <");
        String _TN_4 = this.TN((degree).intValue());
        _builder_2.append(_TN_4, "    ");
        _builder_2.append("> SelectSelectStep<Record");
        _builder_2.append(degree, "    ");
        _builder_2.append("<");
        String _TN_5 = this.TN((degree).intValue());
        _builder_2.append(_TN_5, "    ");
        _builder_2.append(">> selectDistinct(");
        String _SelectField_TN_fieldn_2 = this.SelectField_TN_fieldn((degree).intValue());
        _builder_2.append(_SelectField_TN_fieldn_2, "    ");
        _builder_2.append(") {");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("        ");
        _builder_2.append("return (SelectSelectStep) selectDistinct(new SelectField[] { ");
        String _fieldn_1 = this.fieldn((degree).intValue());
        _builder_2.append(_fieldn_1, "        ");
        _builder_2.append(" });");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("    ");
        _builder_2.append("}");
        _builder_2.newLine();
        outImpl.append(_builder_2);
      }
    }
    this.insert("org.jooq.DSLContext", outAPI, "selectDistinct");
    this.insert("org.jooq.impl.DefaultDSLContext", outImpl, "selectDistinct");
    this.insert("org.jooq.impl.DSL", outDSL, "selectDistinct");
  }
  
  public void generateInsert() {
    final StringBuilder outDSL = new StringBuilder();
    final StringBuilder outImpl = new StringBuilder();
    final StringBuilder outAPI = new StringBuilder();
    IntegerRange _upTo = new IntegerRange(1, Constants.MAX_ROW_DEGREE);
    for (final Integer degree : _upTo) {
      {
        StringConcatenation _builder = new StringConcatenation();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("/**");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* Create a new DSL insert statement.");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <p>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* Example: <code><pre>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* using(configuration)");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*       .insertInto(table, ");
        String _field1_field2_fieldn = this.field1_field2_fieldn((degree).intValue());
        _builder.append(_field1_field2_fieldn, "     ");
        _builder.append(")");
        _builder.newLineIfNotEmpty();
        _builder.append("     ");
        _builder.append("*       .values(");
        String _XXX1_XXX2_XXXn = this.XXX1_XXX2_XXXn((degree).intValue(), "valueA");
        _builder.append(_XXX1_XXX2_XXXn, "     ");
        _builder.append(")");
        _builder.newLineIfNotEmpty();
        _builder.append("     ");
        _builder.append("*       .values(");
        String _XXX1_XXX2_XXXn_1 = this.XXX1_XXX2_XXXn((degree).intValue(), "valueB");
        _builder.append(_XXX1_XXX2_XXXn_1, "     ");
        _builder.append(")");
        _builder.newLineIfNotEmpty();
        _builder.append("     ");
        _builder.append("*       .onDuplicateKeyUpdate()");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*       .set(field1, value1)");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*       .set(field2, value2)");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*       .execute();");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* </pre></code>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*/");
        _builder.newLine();
        _builder.append("    ");
        CharSequence _generatedMethod = this.generatedMethod();
        _builder.append(_generatedMethod, "    ");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("@Support");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<R extends Record, ");
        String _TN = this.TN((degree).intValue());
        _builder.append(_TN, "    ");
        _builder.append("> InsertValuesStep");
        _builder.append(degree, "    ");
        _builder.append("<R, ");
        String _TN_1 = this.TN((degree).intValue());
        _builder.append(_TN_1, "    ");
        _builder.append("> insertInto(Table<R> into, ");
        String _Field_TN_fieldn = this.Field_TN_fieldn((degree).intValue());
        _builder.append(_Field_TN_fieldn, "    ");
        _builder.append(");");
        _builder.newLineIfNotEmpty();
        outAPI.append(_builder);
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.newLine();
        _builder_1.append("    ");
        _builder_1.append("/**");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* Create a new DSL insert statement.");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <p>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* Unlike {@link Insert} factory methods in the {@link DSLContext} API, this");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* creates an unattached, and thus not directly renderable or executable");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <code>INSERT</code> statement.");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <p>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* Example: <code><pre>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* import static org.jooq.impl.DSL.*;");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* // [...]");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* insertInto(table, ");
        String _field1_field2_fieldn_1 = this.field1_field2_fieldn((degree).intValue());
        _builder_1.append(_field1_field2_fieldn_1, "     ");
        _builder_1.append(")");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("     ");
        _builder_1.append("*   .values(");
        String _XXX1_XXX2_XXXn_2 = this.XXX1_XXX2_XXXn((degree).intValue(), "valueA");
        _builder_1.append(_XXX1_XXX2_XXXn_2, "     ");
        _builder_1.append(")");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("     ");
        _builder_1.append("*   .values(");
        String _XXX1_XXX2_XXXn_3 = this.XXX1_XXX2_XXXn((degree).intValue(), "valueB");
        _builder_1.append(_XXX1_XXX2_XXXn_3, "     ");
        _builder_1.append(")");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("     ");
        _builder_1.append("*   .onDuplicateKeyUpdate()");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*   .set(field1, value1)");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*   .set(field2, value2)");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* </pre></code>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* @see DSLContext#insertInto(Table, ");
        IntegerRange _upTo_1 = new IntegerRange(1, (degree).intValue());
        final Function1<Integer, String> _function = (Integer e) -> {
          return "Field";
        };
        Iterable<String> _map = IterableExtensions.<Integer, String>map(_upTo_1, _function);
        String _join = IterableExtensions.join(_map, ", ");
        _builder_1.append(_join, "     ");
        _builder_1.append(")");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("     ");
        _builder_1.append("*/");
        _builder_1.newLine();
        _builder_1.append("    ");
        CharSequence _generatedMethod_1 = this.generatedMethod();
        _builder_1.append(_generatedMethod_1, "    ");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    ");
        _builder_1.append("@Support");
        _builder_1.newLine();
        _builder_1.append("    ");
        _builder_1.append("public static <R extends Record, ");
        String _TN_2 = this.TN((degree).intValue());
        _builder_1.append(_TN_2, "    ");
        _builder_1.append("> InsertValuesStep");
        _builder_1.append(degree, "    ");
        _builder_1.append("<R, ");
        String _TN_3 = this.TN((degree).intValue());
        _builder_1.append(_TN_3, "    ");
        _builder_1.append("> insertInto(Table<R> into, ");
        String _Field_TN_fieldn_1 = this.Field_TN_fieldn((degree).intValue());
        _builder_1.append(_Field_TN_fieldn_1, "    ");
        _builder_1.append(") {");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("        ");
        _builder_1.append("return (InsertValuesStep");
        _builder_1.append(degree, "        ");
        _builder_1.append(") insertInto(into, new Field[] { ");
        String _fieldn = this.fieldn((degree).intValue());
        _builder_1.append(_fieldn, "        ");
        _builder_1.append(" });");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    ");
        _builder_1.append("}");
        _builder_1.newLine();
        outDSL.append(_builder_1);
        StringConcatenation _builder_2 = new StringConcatenation();
        _builder_2.newLine();
        _builder_2.append("    ");
        CharSequence _generatedMethod_2 = this.generatedMethod();
        _builder_2.append(_generatedMethod_2, "    ");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("    ");
        _builder_2.append("@Override");
        _builder_2.newLine();
        _builder_2.append("    ");
        _builder_2.append("public <R extends Record, ");
        String _TN_4 = this.TN((degree).intValue());
        _builder_2.append(_TN_4, "    ");
        _builder_2.append("> InsertValuesStep");
        _builder_2.append(degree, "    ");
        _builder_2.append("<R, ");
        String _TN_5 = this.TN((degree).intValue());
        _builder_2.append(_TN_5, "    ");
        _builder_2.append("> insertInto(Table<R> into, ");
        String _Field_TN_fieldn_2 = this.Field_TN_fieldn((degree).intValue());
        _builder_2.append(_Field_TN_fieldn_2, "    ");
        _builder_2.append(") {");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("        ");
        _builder_2.append("return new InsertImpl(configuration(), into, Arrays.asList(new Field[] { ");
        String _fieldn_1 = this.fieldn((degree).intValue());
        _builder_2.append(_fieldn_1, "        ");
        _builder_2.append(" }));");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("    ");
        _builder_2.append("}");
        _builder_2.newLine();
        outImpl.append(_builder_2);
      }
    }
    this.insert("org.jooq.DSLContext", outAPI, "insert");
    this.insert("org.jooq.impl.DefaultDSLContext", outImpl, "insert");
    this.insert("org.jooq.impl.DSL", outDSL, "insert");
  }
  
  public void generateMerge() {
    final StringBuilder outDSL = new StringBuilder();
    final StringBuilder outImpl = new StringBuilder();
    final StringBuilder outAPI = new StringBuilder();
    IntegerRange _upTo = new IntegerRange(1, Constants.MAX_ROW_DEGREE);
    for (final Integer degree : _upTo) {
      {
        StringConcatenation _builder = new StringConcatenation();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("/**");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* Create a new DSL merge statement (H2-specific syntax).");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <p>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* This statement is available from DSL syntax only. It is known to be");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* supported in some way by any of these dialects:");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <table border=\"1\">");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <tr>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <td>H2</td>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <td>H2 natively supports this special syntax</td>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <td><a href= \"www.h2database.com/html/grammar.html#merge\"");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* >www.h2database.com/html/grammar.html#merge</a></td>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* </tr>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <tr>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <td>DB2, HSQLDB, Oracle, SQL Server, Sybase SQL Anywhere</td>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <td>These databases can simulate the H2-specific MERGE statement using a");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* standard SQL MERGE statement, without restrictions</td>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* <td>See {@link #mergeInto(Table)} for the standard MERGE statement</td>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* </tr>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* </table>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*/");
        _builder.newLine();
        _builder.append("    ");
        CharSequence _generatedMethod = this.generatedMethod();
        _builder.append(_generatedMethod, "    ");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("@Support({ CUBRID, DB2, H2, HSQLDB, INFORMIX, ORACLE, SQLSERVER, SYBASE })");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<R extends Record, ");
        String _TN = this.TN((degree).intValue());
        _builder.append(_TN, "    ");
        _builder.append("> MergeKeyStep");
        _builder.append(degree, "    ");
        _builder.append("<R, ");
        String _TN_1 = this.TN((degree).intValue());
        _builder.append(_TN_1, "    ");
        _builder.append("> mergeInto(Table<R> table, ");
        String _Field_TN_fieldn = this.Field_TN_fieldn((degree).intValue());
        _builder.append(_Field_TN_fieldn, "    ");
        _builder.append(");");
        _builder.newLineIfNotEmpty();
        outAPI.append(_builder);
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.newLine();
        _builder_1.append("    ");
        _builder_1.append("/**");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* Create a new DSL merge statement (H2-specific syntax).");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <p>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* Unlike {@link Merge} factory methods in the {@link DSLContext} API, this");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* creates an unattached, and thus not directly renderable or executable");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <code>MERGE</code> statement.");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <p>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* This statement is available from DSL syntax only. It is known to be");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* supported in some way by any of these dialects:");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <table border=\"1\">");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <tr>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <td>H2</td>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <td>H2 natively supports this special syntax</td>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <td><a href= \"www.h2database.com/html/grammar.html#merge\"");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* >www.h2database.com/html/grammar.html#merge</a></td>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* </tr>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <tr>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <td>DB2, HSQLDB, Oracle, SQL Server, Sybase SQL Anywhere</td>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <td>These databases can simulate the H2-specific MERGE statement using a");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* standard SQL MERGE statement, without restrictions</td>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* <td>See {@link #mergeInto(Table)} for the standard MERGE statement</td>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* </tr>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* </table>");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("*");
        _builder_1.newLine();
        _builder_1.append("     ");
        _builder_1.append("* @see DSLContext#mergeInto(Table, ");
        IntegerRange _upTo_1 = new IntegerRange(1, (degree).intValue());
        final Function1<Integer, String> _function = (Integer e) -> {
          return "Field";
        };
        Iterable<String> _map = IterableExtensions.<Integer, String>map(_upTo_1, _function);
        String _join = IterableExtensions.join(_map, ", ");
        _builder_1.append(_join, "     ");
        _builder_1.append(")");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("     ");
        _builder_1.append("*/");
        _builder_1.newLine();
        _builder_1.append("    ");
        CharSequence _generatedMethod_1 = this.generatedMethod();
        _builder_1.append(_generatedMethod_1, "    ");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    ");
        _builder_1.append("@Support({ CUBRID, DB2, H2, HSQLDB, INFORMIX, ORACLE, SQLSERVER, SYBASE })");
        _builder_1.newLine();
        _builder_1.append("    ");
        _builder_1.append("public static <R extends Record, ");
        String _TN_2 = this.TN((degree).intValue());
        _builder_1.append(_TN_2, "    ");
        _builder_1.append("> MergeKeyStep");
        _builder_1.append(degree, "    ");
        _builder_1.append("<R, ");
        String _TN_3 = this.TN((degree).intValue());
        _builder_1.append(_TN_3, "    ");
        _builder_1.append("> mergeInto(Table<R> table, ");
        String _Field_TN_fieldn_1 = this.Field_TN_fieldn((degree).intValue());
        _builder_1.append(_Field_TN_fieldn_1, "    ");
        _builder_1.append(") {");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    \t");
        _builder_1.append("return using(new DefaultConfiguration()).mergeInto(table, ");
        String _fieldn = this.fieldn((degree).intValue());
        _builder_1.append(_fieldn, "    \t");
        _builder_1.append(");");
        _builder_1.newLineIfNotEmpty();
        _builder_1.append("    ");
        _builder_1.append("}");
        _builder_1.newLine();
        outDSL.append(_builder_1);
        StringConcatenation _builder_2 = new StringConcatenation();
        _builder_2.newLine();
        _builder_2.append("    ");
        CharSequence _generatedMethod_2 = this.generatedMethod();
        _builder_2.append(_generatedMethod_2, "    ");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("    ");
        _builder_2.append("@Override");
        _builder_2.newLine();
        _builder_2.append("    ");
        _builder_2.append("public <R extends Record, ");
        String _TN_4 = this.TN((degree).intValue());
        _builder_2.append(_TN_4, "    ");
        _builder_2.append("> MergeKeyStep");
        _builder_2.append(degree, "    ");
        _builder_2.append("<R, ");
        String _TN_5 = this.TN((degree).intValue());
        _builder_2.append(_TN_5, "    ");
        _builder_2.append("> mergeInto(Table<R> table, ");
        String _Field_TN_fieldn_2 = this.Field_TN_fieldn((degree).intValue());
        _builder_2.append(_Field_TN_fieldn_2, "    ");
        _builder_2.append(") {");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("        ");
        _builder_2.append("return new MergeImpl(configuration(), table, Arrays.asList(");
        String _fieldn_1 = this.fieldn((degree).intValue());
        _builder_2.append(_fieldn_1, "        ");
        _builder_2.append("));");
        _builder_2.newLineIfNotEmpty();
        _builder_2.append("    ");
        _builder_2.append("}");
        _builder_2.newLine();
        outImpl.append(_builder_2);
      }
    }
    this.insert("org.jooq.DSLContext", outAPI, "merge");
    this.insert("org.jooq.impl.DefaultDSLContext", outImpl, "merge");
    this.insert("org.jooq.impl.DSL", outDSL, "merge");
  }
}
