DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER(
  ID NUMBER(7)    NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR (20) NOT NULL,
  EMAIL VARCHAR (50),
CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT (
  ID NUMBER(7)      NOT NULL PRIMARY KEY AUTO_INCREMENT,
  PRODUCT_NAME VARCHAR (20),
  CUSTOMER_ID NUMBER(7),
  CONSTRAINT PRODUCT_PK PRIMARY KEY (ID),
  CONSTRAINT PRODUCT_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);
