/**
 * This class is generated by jOOQ
 */
package org.jooq.test.cubrid.generatedclasses;


import org.jooq.test.cubrid.generatedclasses.tables.TAuthor;
import org.jooq.test.cubrid.generatedclasses.tables.TBook;
import org.jooq.test.cubrid.generatedclasses.tables.TBookStore;
import org.jooq.test.cubrid.generatedclasses.tables.TBookToBookStore;
import org.jooq.test.cubrid.generatedclasses.tables.TBooleans;
import org.jooq.test.cubrid.generatedclasses.tables.TDates;
import org.jooq.test.cubrid.generatedclasses.tables.TDirectory;
import org.jooq.test.cubrid.generatedclasses.tables.TExoticTypes;
import org.jooq.test.cubrid.generatedclasses.tables.TIdentity;
import org.jooq.test.cubrid.generatedclasses.tables.TIdentityPk;
import org.jooq.test.cubrid.generatedclasses.tables.TLanguage;
import org.jooq.test.cubrid.generatedclasses.tables.TTriggers;
import org.jooq.test.cubrid.generatedclasses.tables.TUnsigned;
import org.jooq.test.cubrid.generatedclasses.tables.T_639NumbersTable;
import org.jooq.test.cubrid.generatedclasses.tables.T_725LobTest;
import org.jooq.test.cubrid.generatedclasses.tables.T_785;
import org.jooq.test.cubrid.generatedclasses.tables.T_959;
import org.jooq.test.cubrid.generatedclasses.tables.T_986_1;
import org.jooq.test.cubrid.generatedclasses.tables.T_986_2;
import org.jooq.test.cubrid.generatedclasses.tables.VAuthor;
import org.jooq.test.cubrid.generatedclasses.tables.VBook;
import org.jooq.test.cubrid.generatedclasses.tables.VLibrary;
import org.jooq.test.cubrid.generatedclasses.tables.XTestCase_2025;
import org.jooq.test.cubrid.generatedclasses.tables.XTestCase_64_69;
import org.jooq.test.cubrid.generatedclasses.tables.XTestCase_71;
import org.jooq.test.cubrid.generatedclasses.tables.XTestCase_85;
import org.jooq.test.cubrid.generatedclasses.tables.XUnused;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table t_639_numbers_table
	 */
	public static final T_639NumbersTable T_639_NUMBERS_TABLE = org.jooq.test.cubrid.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE;

	/**
	 * The table t_725_lob_test
	 */
	public static final T_725LobTest T_725_LOB_TEST = org.jooq.test.cubrid.generatedclasses.tables.T_725LobTest.T_725_LOB_TEST;

	/**
	 * The table t_785
	 */
	public static final T_785 T_785 = org.jooq.test.cubrid.generatedclasses.tables.T_785.T_785;

	/**
	 * The table t_959
	 */
	public static final T_959 T_959 = org.jooq.test.cubrid.generatedclasses.tables.T_959.T_959;

	/**
	 * The table t_986_1
	 */
	public static final T_986_1 T_986_1 = org.jooq.test.cubrid.generatedclasses.tables.T_986_1.T_986_1;

	/**
	 * The table t_986_2
	 */
	public static final T_986_2 T_986_2 = org.jooq.test.cubrid.generatedclasses.tables.T_986_2.T_986_2;

	/**
	 * The table t_author
	 */
	public static final TAuthor T_AUTHOR = org.jooq.test.cubrid.generatedclasses.tables.TAuthor.T_AUTHOR;

	/**
	 * The table t_book
	 */
	public static final TBook T_BOOK = org.jooq.test.cubrid.generatedclasses.tables.TBook.T_BOOK;

	/**
	 * The table t_book_store
	 */
	public static final TBookStore T_BOOK_STORE = org.jooq.test.cubrid.generatedclasses.tables.TBookStore.T_BOOK_STORE;

	/**
	 * The table t_book_to_book_store
	 */
	public static final TBookToBookStore T_BOOK_TO_BOOK_STORE = org.jooq.test.cubrid.generatedclasses.tables.TBookToBookStore.T_BOOK_TO_BOOK_STORE;

	/**
	 * The table t_booleans
	 */
	public static final TBooleans T_BOOLEANS = org.jooq.test.cubrid.generatedclasses.tables.TBooleans.T_BOOLEANS;

	/**
	 * The table t_dates
	 */
	public static final TDates T_DATES = org.jooq.test.cubrid.generatedclasses.tables.TDates.T_DATES;

	/**
	 * The table t_directory
	 */
	public static final TDirectory T_DIRECTORY = org.jooq.test.cubrid.generatedclasses.tables.TDirectory.T_DIRECTORY;

	/**
	 * The table t_exotic_types
	 */
	public static final TExoticTypes T_EXOTIC_TYPES = org.jooq.test.cubrid.generatedclasses.tables.TExoticTypes.T_EXOTIC_TYPES;

	/**
	 * The table t_identity
	 */
	public static final TIdentity T_IDENTITY = org.jooq.test.cubrid.generatedclasses.tables.TIdentity.T_IDENTITY;

	/**
	 * The table t_identity_pk
	 */
	public static final TIdentityPk T_IDENTITY_PK = org.jooq.test.cubrid.generatedclasses.tables.TIdentityPk.T_IDENTITY_PK;

	/**
	 * The table t_language
	 */
	public static final TLanguage T_LANGUAGE = org.jooq.test.cubrid.generatedclasses.tables.TLanguage.T_LANGUAGE;

	/**
	 * The table t_triggers
	 */
	public static final TTriggers T_TRIGGERS = org.jooq.test.cubrid.generatedclasses.tables.TTriggers.T_TRIGGERS;

	/**
	 * The table t_unsigned
	 */
	public static final TUnsigned T_UNSIGNED = org.jooq.test.cubrid.generatedclasses.tables.TUnsigned.T_UNSIGNED;

	/**
	 * The table v_author
	 */
	public static final VAuthor V_AUTHOR = org.jooq.test.cubrid.generatedclasses.tables.VAuthor.V_AUTHOR;

	/**
	 * The table v_book
	 */
	public static final VBook V_BOOK = org.jooq.test.cubrid.generatedclasses.tables.VBook.V_BOOK;

	/**
	 * The table v_library
	 */
	public static final VLibrary V_LIBRARY = org.jooq.test.cubrid.generatedclasses.tables.VLibrary.V_LIBRARY;

	/**
	 * The table x_test_case_2025
	 */
	public static final XTestCase_2025 X_TEST_CASE_2025 = org.jooq.test.cubrid.generatedclasses.tables.XTestCase_2025.X_TEST_CASE_2025;

	/**
	 * The table x_test_case_64_69
	 */
	public static final XTestCase_64_69 X_TEST_CASE_64_69 = org.jooq.test.cubrid.generatedclasses.tables.XTestCase_64_69.X_TEST_CASE_64_69;

	/**
	 * The table x_test_case_71
	 */
	public static final XTestCase_71 X_TEST_CASE_71 = org.jooq.test.cubrid.generatedclasses.tables.XTestCase_71.X_TEST_CASE_71;

	/**
	 * The table x_test_case_85
	 */
	public static final XTestCase_85 X_TEST_CASE_85 = org.jooq.test.cubrid.generatedclasses.tables.XTestCase_85.X_TEST_CASE_85;

	/**
	 * The table x_unused
	 */
	public static final XUnused X_UNUSED = org.jooq.test.cubrid.generatedclasses.tables.XUnused.X_UNUSED;
}
