/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oraclescala.generatedclasses.test.routines


import java.lang.Number
import java.lang.String
import java.math.BigDecimal

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.test.oraclescala.generatedclasses.test.Test


object PUnused {

	/**
	 * The parameter <code>TEST.P_UNUSED.IN1</code>.
	 */
	val IN1 : Parameter[String] = AbstractRoutine.createParameter("IN1", org.jooq.impl.SQLDataType.VARCHAR, false)

	/**
	 * The parameter <code>TEST.P_UNUSED.OUT1</code>.
	 */
	val OUT1 : Parameter[BigDecimal] = AbstractRoutine.createParameter("OUT1", org.jooq.impl.SQLDataType.NUMERIC, false)

	/**
	 * The parameter <code>TEST.P_UNUSED.OUT2</code>.
	 */
	val OUT2 : Parameter[BigDecimal] = AbstractRoutine.createParameter("OUT2", org.jooq.impl.SQLDataType.NUMERIC, false)
}

/**
 * This class is generated by jOOQ.
 */
class PUnused extends AbstractRoutine[java.lang.Void]("P_UNUSED", Test.TEST) {
	{
		addInParameter(PUnused.IN1)
		addOutParameter(PUnused.OUT1)
		addInOutParameter(PUnused.OUT2)
	}

	/**
	 * Set the <code>IN1</code> parameter IN value to the routine
	 */
	def setIn1(value : String) : Unit = {
		setValue(PUnused.IN1, value)
	}

	/**
	 * Set the <code>OUT2</code> parameter IN value to the routine
	 */
	def setOut2(value : Number) : Unit = {
		setNumber(PUnused.OUT2, value)
	}

	/**
	 * Get the <code>OUT1</code> parameter OUT value from the routine
	 */
	def getOut1 : BigDecimal = {
		getValue(PUnused.OUT1)
	}

	/**
	 * Get the <code>OUT2</code> parameter OUT value from the routine
	 */
	def getOut2 : BigDecimal = {
		getValue(PUnused.OUT2)
	}
}
