/**
 * This class is generated by jOOQ
 */
package org.jooq.example.gradle.db.information_schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.5.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemataRecord extends org.jooq.impl.TableRecordImpl<org.jooq.example.gradle.db.information_schema.tables.records.SchemataRecord> implements org.jooq.Record8<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 2040453423;

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SCHEMATA.CATALOG_NAME</code>.
	 */
	public void setCatalogName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SCHEMATA.CATALOG_NAME</code>.
	 */
	public java.lang.String getCatalogName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SCHEMATA.SCHEMA_NAME</code>.
	 */
	public void setSchemaName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SCHEMATA.SCHEMA_NAME</code>.
	 */
	public java.lang.String getSchemaName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SCHEMATA.SCHEMA_OWNER</code>.
	 */
	public void setSchemaOwner(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SCHEMATA.SCHEMA_OWNER</code>.
	 */
	public java.lang.String getSchemaOwner() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SCHEMATA.DEFAULT_CHARACTER_SET_NAME</code>.
	 */
	public void setDefaultCharacterSetName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SCHEMATA.DEFAULT_CHARACTER_SET_NAME</code>.
	 */
	public java.lang.String getDefaultCharacterSetName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SCHEMATA.DEFAULT_COLLATION_NAME</code>.
	 */
	public void setDefaultCollationName(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SCHEMATA.DEFAULT_COLLATION_NAME</code>.
	 */
	public java.lang.String getDefaultCollationName() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SCHEMATA.IS_DEFAULT</code>.
	 */
	public void setIsDefault(java.lang.Boolean value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SCHEMATA.IS_DEFAULT</code>.
	 */
	public java.lang.Boolean getIsDefault() {
		return (java.lang.Boolean) getValue(5);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SCHEMATA.REMARKS</code>.
	 */
	public void setRemarks(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SCHEMATA.REMARKS</code>.
	 */
	public java.lang.String getRemarks() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>INFORMATION_SCHEMA.SCHEMATA.ID</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>INFORMATION_SCHEMA.SCHEMATA.ID</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return org.jooq.example.gradle.db.information_schema.tables.Schemata.SCHEMATA.CATALOG_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.jooq.example.gradle.db.information_schema.tables.Schemata.SCHEMATA.SCHEMA_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.jooq.example.gradle.db.information_schema.tables.Schemata.SCHEMATA.SCHEMA_OWNER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.jooq.example.gradle.db.information_schema.tables.Schemata.SCHEMATA.DEFAULT_CHARACTER_SET_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.jooq.example.gradle.db.information_schema.tables.Schemata.SCHEMATA.DEFAULT_COLLATION_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field6() {
		return org.jooq.example.gradle.db.information_schema.tables.Schemata.SCHEMATA.IS_DEFAULT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return org.jooq.example.gradle.db.information_schema.tables.Schemata.SCHEMATA.REMARKS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return org.jooq.example.gradle.db.information_schema.tables.Schemata.SCHEMATA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getCatalogName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSchemaName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSchemaOwner();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDefaultCharacterSetName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getDefaultCollationName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value6() {
		return getIsDefault();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getRemarks();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemataRecord value1(java.lang.String value) {
		setCatalogName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemataRecord value2(java.lang.String value) {
		setSchemaName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemataRecord value3(java.lang.String value) {
		setSchemaOwner(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemataRecord value4(java.lang.String value) {
		setDefaultCharacterSetName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemataRecord value5(java.lang.String value) {
		setDefaultCollationName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemataRecord value6(java.lang.Boolean value) {
		setIsDefault(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemataRecord value7(java.lang.String value) {
		setRemarks(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemataRecord value8(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchemataRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.Boolean value6, java.lang.String value7, java.lang.Integer value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SchemataRecord
	 */
	public SchemataRecord() {
		super(org.jooq.example.gradle.db.information_schema.tables.Schemata.SCHEMATA);
	}

	/**
	 * Create a detached, initialised SchemataRecord
	 */
	public SchemataRecord(java.lang.String catalogName, java.lang.String schemaName, java.lang.String schemaOwner, java.lang.String defaultCharacterSetName, java.lang.String defaultCollationName, java.lang.Boolean isDefault, java.lang.String remarks, java.lang.Integer id) {
		super(org.jooq.example.gradle.db.information_schema.tables.Schemata.SCHEMATA);

		setValue(0, catalogName);
		setValue(1, schemaName);
		setValue(2, schemaOwner);
		setValue(3, defaultCharacterSetName);
		setValue(4, defaultCollationName);
		setValue(5, isDefault);
		setValue(6, remarks);
		setValue(7, id);
	}
}
