/**
 * This class is generated by jOOQ
 */
package org.jooq.examples.sqlserver.adventureworks.humanresources.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.persistence.Entity
@javax.persistence.Table(name = "Department", schema = "HumanResources")
public class Department implements java.io.Serializable {

	private static final long serialVersionUID = -1174085215;

	private java.lang.Short    DepartmentID;
	private java.lang.String   Name;
	private java.lang.String   GroupName;
	private java.sql.Timestamp ModifiedDate;

	public Department() {}

	public Department(
		java.lang.Short    DepartmentID,
		java.lang.String   Name,
		java.lang.String   GroupName,
		java.sql.Timestamp ModifiedDate
	) {
		this.DepartmentID = DepartmentID;
		this.Name = Name;
		this.GroupName = GroupName;
		this.ModifiedDate = ModifiedDate;
	}

	@javax.persistence.Id
	@javax.persistence.Column(name = "DepartmentID", unique = true, nullable = false, precision = 5)
	@javax.validation.constraints.NotNull
	public java.lang.Short getDepartmentID() {
		return this.DepartmentID;
	}

	public void setDepartmentID(java.lang.Short DepartmentID) {
		this.DepartmentID = DepartmentID;
	}

	@javax.persistence.Column(name = "Name", nullable = false, length = 50)
	@javax.validation.constraints.NotNull
	@javax.validation.constraints.Size(max = 50)
	public java.lang.String getName() {
		return this.Name;
	}

	public void setName(java.lang.String Name) {
		this.Name = Name;
	}

	@javax.persistence.Column(name = "GroupName", nullable = false, length = 50)
	@javax.validation.constraints.NotNull
	@javax.validation.constraints.Size(max = 50)
	public java.lang.String getGroupName() {
		return this.GroupName;
	}

	public void setGroupName(java.lang.String GroupName) {
		this.GroupName = GroupName;
	}

	@javax.persistence.Column(name = "ModifiedDate", nullable = false)
	@javax.validation.constraints.NotNull
	public java.sql.Timestamp getModifiedDate() {
		return this.ModifiedDate;
	}

	public void setModifiedDate(java.sql.Timestamp ModifiedDate) {
		this.ModifiedDate = ModifiedDate;
	}
}
