/**
 * This class is generated by jOOQ
 */
package org.jooq.test.sybase.generatedclasses.tables.records;

/**
 * This class is generated by jOOQ.
 */
public class T_639NumbersTableRecord extends org.jooq.impl.UpdatableRecordImpl<org.jooq.test.sybase.generatedclasses.tables.records.T_639NumbersTableRecord> {

	private static final long serialVersionUID = 323740478;

	/**
	 * The table column <code>DBA.t_639_numbers_table.ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.ID, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.ID);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.BYTE</code>
	 */
	public void setByte(java.lang.Byte value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.BYTE, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.BYTE</code>
	 */
	public java.lang.Byte getByte() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.BYTE);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.SHORT</code>
	 */
	public void setShort(java.lang.Short value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.SHORT, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.SHORT</code>
	 */
	public java.lang.Short getShort() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.SHORT);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.INTEGER</code>
	 */
	public void setInteger(java.lang.Integer value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.INTEGER, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.INTEGER</code>
	 */
	public java.lang.Integer getInteger() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.INTEGER);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.LONG</code>
	 */
	public void setLong(java.lang.Long value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.LONG, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.LONG</code>
	 */
	public java.lang.Long getLong() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.LONG);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.BYTE_DECIMAL</code>
	 */
	public void setByteDecimal(java.lang.Byte value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.BYTE_DECIMAL, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.BYTE_DECIMAL</code>
	 */
	public java.lang.Byte getByteDecimal() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.BYTE_DECIMAL);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.SHORT_DECIMAL</code>
	 */
	public void setShortDecimal(java.lang.Short value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.SHORT_DECIMAL, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.SHORT_DECIMAL</code>
	 */
	public java.lang.Short getShortDecimal() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.SHORT_DECIMAL);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.INTEGER_DECIMAL</code>
	 */
	public void setIntegerDecimal(java.lang.Integer value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.INTEGER_DECIMAL, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.INTEGER_DECIMAL</code>
	 */
	public java.lang.Integer getIntegerDecimal() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.INTEGER_DECIMAL);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.LONG_DECIMAL</code>
	 */
	public void setLongDecimal(java.lang.Long value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.LONG_DECIMAL, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.LONG_DECIMAL</code>
	 */
	public java.lang.Long getLongDecimal() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.LONG_DECIMAL);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.BIG_INTEGER</code>
	 */
	public void setBigInteger(java.math.BigInteger value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.BIG_INTEGER, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.BIG_INTEGER</code>
	 */
	public java.math.BigInteger getBigInteger() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.BIG_INTEGER);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.BIG_DECIMAL</code>
	 */
	public void setBigDecimal(java.math.BigDecimal value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.BIG_DECIMAL, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.BIG_DECIMAL</code>
	 */
	public java.math.BigDecimal getBigDecimal() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.BIG_DECIMAL);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.FLOAT</code>
	 */
	public void setFloat(java.lang.Double value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.FLOAT, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.FLOAT</code>
	 */
	public java.lang.Double getFloat() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.FLOAT);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.DOUBLE</code>
	 */
	public void setDouble(java.lang.Double value) {
		setValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.DOUBLE, value);
	}

	/**
	 * The table column <code>DBA.t_639_numbers_table.DOUBLE</code>
	 */
	public java.lang.Double getDouble() {
		return getValue(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE.DOUBLE);
	}

	/**
	 * Create a detached T_639NumbersTableRecord
	 */
	public T_639NumbersTableRecord() {
		super(org.jooq.test.sybase.generatedclasses.tables.T_639NumbersTable.T_639_NUMBERS_TABLE);
	}
}
