/**
 * This class is generated by jOOQ
 */
package org.jooq.test.firebird.generatedclasses;

/**
 * Convenience access to all stored procedures and functions in 
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

	/**
	 * Call <code>P_AUTHOR_EXISTS</code>
	 */
	public static java.lang.Integer pAuthorExists(org.jooq.Configuration configuration, java.lang.String authorName) {
		org.jooq.test.firebird.generatedclasses.routines.PAuthorExists p = new org.jooq.test.firebird.generatedclasses.routines.PAuthorExists();
		p.setAuthorName(authorName);

		p.execute(configuration);
		return p.getResult();
	}

	/**
	 * Call <code>P_CREATE_AUTHOR</code>
	 */
	public static void pCreateAuthor(org.jooq.Configuration configuration) {
		org.jooq.test.firebird.generatedclasses.routines.PCreateAuthor p = new org.jooq.test.firebird.generatedclasses.routines.PCreateAuthor();

		p.execute(configuration);
	}

	/**
	 * Call <code>P_CREATE_AUTHOR_BY_NAME</code>
	 */
	public static void pCreateAuthorByName(org.jooq.Configuration configuration, java.lang.String firstName, java.lang.String lastName) {
		org.jooq.test.firebird.generatedclasses.routines.PCreateAuthorByName p = new org.jooq.test.firebird.generatedclasses.routines.PCreateAuthorByName();
		p.setFirstName(firstName);
		p.setLastName(lastName);

		p.execute(configuration);
	}

	/**
	 * Get <code>F_TABLES1</code> as a field
	 */
	public static org.jooq.test.firebird.generatedclasses.tables.FTables1 fTables1() {
		return org.jooq.test.firebird.generatedclasses.tables.FTables1.F_TABLES1.call();
	}

	/**
	 * Get <code>F_TABLES2</code> as a field
	 */
	public static org.jooq.test.firebird.generatedclasses.tables.FTables2 fTables2() {
		return org.jooq.test.firebird.generatedclasses.tables.FTables2.F_TABLES2.call();
	}

	/**
	 * Get <code>F_TABLES3</code> as a field
	 */
	public static org.jooq.test.firebird.generatedclasses.tables.FTables3 fTables3() {
		return org.jooq.test.firebird.generatedclasses.tables.FTables3.F_TABLES3.call();
	}

	/**
	 * Get <code>F_TABLES4</code> as a field
	 */
	public static org.jooq.test.firebird.generatedclasses.tables.FTables4 fTables4(java.lang.Integer pId) {
		return org.jooq.test.firebird.generatedclasses.tables.FTables4.F_TABLES4.call(pId);
	}

	/**
	 * Get <code>F_TABLES4</code> as a field
	 */
	public static org.jooq.test.firebird.generatedclasses.tables.FTables4 fTables4(org.jooq.Field<java.lang.Integer> pId) {
		return org.jooq.test.firebird.generatedclasses.tables.FTables4.F_TABLES4.call(pId);
	}

	/**
	 * Get <code>F_TABLES5</code> as a field
	 */
	public static org.jooq.test.firebird.generatedclasses.tables.FTables5 fTables5(java.lang.Integer v1, java.lang.Integer v2, java.lang.Integer v3) {
		return org.jooq.test.firebird.generatedclasses.tables.FTables5.F_TABLES5.call(v1, v2, v3);
	}

	/**
	 * Get <code>F_TABLES5</code> as a field
	 */
	public static org.jooq.test.firebird.generatedclasses.tables.FTables5 fTables5(org.jooq.Field<java.lang.Integer> v1, org.jooq.Field<java.lang.Integer> v2, org.jooq.Field<java.lang.Integer> v3) {
		return org.jooq.test.firebird.generatedclasses.tables.FTables5.F_TABLES5.call(v1, v2, v3);
	}
}
