/**
 * This class is generated by jOOQ
 */
package org.jooq.test.jdbc.generatedclasses.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class V_2603 implements org.jooq.test.jdbc.generatedclasses.tables.interfaces.IV_2603 {

	private static final long serialVersionUID = 755211756;

	private java.lang.Integer col1;
	private java.lang.Integer col2;
	private java.lang.Integer col3;
	private java.lang.Integer col4;

	public V_2603() {}

	public V_2603(
		java.lang.Integer col1,
		java.lang.Integer col2,
		java.lang.Integer col3,
		java.lang.Integer col4
	) {
		this.col1 = col1;
		this.col2 = col2;
		this.col3 = col3;
		this.col4 = col4;
	}

	@Override
	public java.lang.Integer getCol1() {
		return this.col1;
	}

	@Override
	public void setCol1(java.lang.Integer col1) {
		this.col1 = col1;
	}

	@Override
	public java.lang.Integer getCol2() {
		return this.col2;
	}

	@Override
	public void setCol2(java.lang.Integer col2) {
		this.col2 = col2;
	}

	@Override
	public java.lang.Integer getCol3() {
		return this.col3;
	}

	@Override
	public void setCol3(java.lang.Integer col3) {
		this.col3 = col3;
	}

	@Override
	public java.lang.Integer getCol4() {
		return this.col4;
	}

	@Override
	public void setCol4(java.lang.Integer col4) {
		this.col4 = col4;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(org.jooq.test.jdbc.generatedclasses.tables.interfaces.IV_2603 from) {
		setCol1(from.getCol1());
		setCol2(from.getCol2());
		setCol3(from.getCol3());
		setCol4(from.getCol4());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends org.jooq.test.jdbc.generatedclasses.tables.interfaces.IV_2603> E into(E into) {
		into.from(this);
		return into;
	}
}
