/**
 * This class is generated by jOOQ
 */
package org.jooq.test.hsqldb.generatedclasses.tables;

/**
 * This class is generated by jOOQ.
 */
public class System extends org.jooq.impl.TableImpl<org.jooq.test.hsqldb.generatedclasses.tables.records.SystemRecord> {

	private static final long serialVersionUID = 702688949;

	/**
	 * The singleton instance of PUBLIC.SYSTEM
	 */
	public static final org.jooq.test.hsqldb.generatedclasses.tables.System SYSTEM = new org.jooq.test.hsqldb.generatedclasses.tables.System();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<org.jooq.test.hsqldb.generatedclasses.tables.records.SystemRecord> __RECORD_TYPE = org.jooq.test.hsqldb.generatedclasses.tables.records.SystemRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.test.hsqldb.generatedclasses.tables.records.SystemRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<org.jooq.test.hsqldb.generatedclasses.tables.records.SystemRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);

	public System() {
		super("SYSTEM", org.jooq.test.hsqldb.generatedclasses.Public.PUBLIC);
	}

	public System(java.lang.String alias) {
		super(alias, org.jooq.test.hsqldb.generatedclasses.Public.PUBLIC, org.jooq.test.hsqldb.generatedclasses.tables.System.SYSTEM);
	}

	@Override
	public org.jooq.test.hsqldb.generatedclasses.tables.System as(java.lang.String alias) {
		return new org.jooq.test.hsqldb.generatedclasses.tables.System(alias);
	}
}
