/**
 * This class is generated by jOOQ
 */
package org.jooq.test.hsqldb.generatedclasses.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TArrays extends org.jooq.impl.TableImpl<org.jooq.test.hsqldb.generatedclasses.tables.records.TArraysRecord> {

	private static final long serialVersionUID = 1615317090;

	/**
	 * The singleton instance of <code>PUBLIC.T_ARRAYS</code>
	 */
	public static final org.jooq.test.hsqldb.generatedclasses.tables.TArrays T_ARRAYS = new org.jooq.test.hsqldb.generatedclasses.tables.TArrays();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.test.hsqldb.generatedclasses.tables.records.TArraysRecord> getRecordType() {
		return org.jooq.test.hsqldb.generatedclasses.tables.records.TArraysRecord.class;
	}

	/**
	 * The column <code>PUBLIC.T_ARRAYS.ID</code>. 
	 */
	public final org.jooq.TableField<org.jooq.test.hsqldb.generatedclasses.tables.records.TArraysRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>PUBLIC.T_ARRAYS.STRING_ARRAY</code>. 
	 */
	public final org.jooq.TableField<org.jooq.test.hsqldb.generatedclasses.tables.records.TArraysRecord, java.lang.String[]> STRING_ARRAY = createField("STRING_ARRAY", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this);

	/**
	 * The column <code>PUBLIC.T_ARRAYS.NUMBER_ARRAY</code>. 
	 */
	public final org.jooq.TableField<org.jooq.test.hsqldb.generatedclasses.tables.records.TArraysRecord, java.lang.Integer[]> NUMBER_ARRAY = createField("NUMBER_ARRAY", org.jooq.impl.SQLDataType.INTEGER.getArrayDataType(), this);

	/**
	 * The column <code>PUBLIC.T_ARRAYS.DATE_ARRAY</code>. 
	 */
	public final org.jooq.TableField<org.jooq.test.hsqldb.generatedclasses.tables.records.TArraysRecord, java.sql.Date[]> DATE_ARRAY = createField("DATE_ARRAY", org.jooq.impl.SQLDataType.DATE.getArrayDataType(), this);

	/**
	 * Create a <code>PUBLIC.T_ARRAYS</code> table reference
	 */
	public TArrays() {
		super("T_ARRAYS", org.jooq.test.hsqldb.generatedclasses.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>PUBLIC.T_ARRAYS</code> table reference
	 */
	public TArrays(java.lang.String alias) {
		super(alias, org.jooq.test.hsqldb.generatedclasses.Public.PUBLIC, org.jooq.test.hsqldb.generatedclasses.tables.TArrays.T_ARRAYS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.test.hsqldb.generatedclasses.tables.records.TArraysRecord> getPrimaryKey() {
		return org.jooq.test.hsqldb.generatedclasses.Keys.PK_T_ARRAYS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.test.hsqldb.generatedclasses.tables.records.TArraysRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.test.hsqldb.generatedclasses.tables.records.TArraysRecord>>asList(org.jooq.test.hsqldb.generatedclasses.Keys.PK_T_ARRAYS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.test.hsqldb.generatedclasses.tables.TArrays as(java.lang.String alias) {
		return new org.jooq.test.hsqldb.generatedclasses.tables.TArrays(alias);
	}
}
