/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle.generatedclasses.test.tables.pojos;


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * An m:n relation between books and book stores
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "T_BOOK_TO_BOOK_STORE", schema = "TEST", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"BOOK_STORE_NAME", "BOOK_ID"})
})
public class TBookToBookStore implements Serializable {

	private static final long serialVersionUID = -1433615202;

	private String  bookStoreName;
	private Integer bookId;
	private Integer stock;

	public TBookToBookStore() {}

	public TBookToBookStore(TBookToBookStore value) {
		this.bookStoreName = value.bookStoreName;
		this.bookId = value.bookId;
		this.stock = value.stock;
	}

	public TBookToBookStore(
		String  bookStoreName,
		Integer bookId,
		Integer stock
	) {
		this.bookStoreName = bookStoreName;
		this.bookId = bookId;
		this.stock = stock;
	}

	@Column(name = "BOOK_STORE_NAME", nullable = false, length = 400)
	@NotNull
	@Size(max = 400)
	public String getBookStoreName() {
		return this.bookStoreName;
	}

	public void setBookStoreName(String bookStoreName) {
		this.bookStoreName = bookStoreName;
	}

	@Column(name = "BOOK_ID", nullable = false, precision = 7)
	@NotNull
	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	@Column(name = "STOCK", precision = 7)
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final TBookToBookStore other = (TBookToBookStore) obj;
		if (bookStoreName == null) {
			if (other.bookStoreName != null)
				return false;
		}
		else if (!bookStoreName.equals(other.bookStoreName))
			return false;
		if (bookId == null) {
			if (other.bookId != null)
				return false;
		}
		else if (!bookId.equals(other.bookId))
			return false;
		if (stock == null) {
			if (other.stock != null)
				return false;
		}
		else if (!stock.equals(other.stock))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bookStoreName == null) ? 0 : bookStoreName.hashCode());
		result = prime * result + ((bookId == null) ? 0 : bookId.hashCode());
		result = prime * result + ((stock == null) ? 0 : stock.hashCode());
		return result;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("TBookToBookStore (");

		sb.append(bookStoreName);
		sb.append(", ").append(bookId);
		sb.append(", ").append(stock);

		sb.append(")");
		return sb.toString();
	}
}
