/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle3.generatedclasses.udt;


import org.jooq.impl.UDTImpl;
import org.jooq.test.oracle3.generatedclasses.DefaultSchema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class U_INVALID_TABLE extends UDTImpl<org.jooq.test.oracle3.generatedclasses.udt.records.U_INVALID_TABLE> implements Cloneable {

	private static final long serialVersionUID = -2036207950;

	/**
	 * The reference instance of <code>U_INVALID_TABLE</code>
	 */
	public static final U_INVALID_TABLE U_INVALID_TABLE = new U_INVALID_TABLE();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<org.jooq.test.oracle3.generatedclasses.udt.records.U_INVALID_TABLE> getRecordType() {
		return org.jooq.test.oracle3.generatedclasses.udt.records.U_INVALID_TABLE.class;
	}

	/**
	 * No further instances allowed
	 */
	private U_INVALID_TABLE() {
		super("U_INVALID_TABLE", DefaultSchema.DEFAULT_SCHEMA);

		// Initialise data type
		getDataType();
	}
}
