/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle.generatedclasses.test.routines;


import java.math.BigDecimal;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.test.oracle.generatedclasses.test.Test;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class F378 extends AbstractRoutine<BigDecimal> {

	private static final long serialVersionUID = -1312631363;

	/**
	 * The parameter <code>TEST.F378.RETURN_VALUE</code>.
	 */
	public static final Parameter<BigDecimal> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>TEST.F378.I</code>.
	 */
	public static final Parameter<BigDecimal> I = createParameter("I", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>TEST.F378.IO</code>.
	 */
	public static final Parameter<BigDecimal> IO = createParameter("IO", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * The parameter <code>TEST.F378.O</code>.
	 */
	public static final Parameter<BigDecimal> O = createParameter("O", org.jooq.impl.SQLDataType.NUMERIC, false);

	/**
	 * Create a new routine call instance
	 */
	public F378() {
		super("F378", Test.TEST, org.jooq.impl.SQLDataType.NUMERIC);

		setReturnParameter(RETURN_VALUE);
		addInParameter(I);
		addInOutParameter(IO);
		addOutParameter(O);
	}

	/**
	 * Set the <code>I</code> parameter IN value to the routine
	 */
	public void setI(Number value) {
		setNumber(I, value);
	}

	/**
	 * Set the <code>IO</code> parameter IN value to the routine
	 */
	public void setIo(Number value) {
		setNumber(IO, value);
	}

	/**
	 * Get the <code>IO</code> parameter OUT value from the routine
	 */
	public BigDecimal getIo() {
		return getValue(IO);
	}

	/**
	 * Get the <code>O</code> parameter OUT value from the routine
	 */
	public BigDecimal getO() {
		return getValue(O);
	}
}
