/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle.generatedclasses.test.udt.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OInvalidType implements Serializable {

	private static final long serialVersionUID = 1962245751;


	public OInvalidType() {}

	public OInvalidType(OInvalidType value) {
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final OInvalidType other = (OInvalidType) obj;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		return result;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("OInvalidType (");


		sb.append(")");
		return sb.toString();
	}
}
