/**
 * This class is generated by jOOQ
 */
package org.jooq.util.ingres.ingres.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Iikeys extends org.jooq.impl.TableImpl<org.jooq.Record> {

	private static final long serialVersionUID = 1690941577;

	/**
	 * The singleton instance of <code>$ingres.iikeys</code>
	 */
	public static final org.jooq.util.ingres.ingres.tables.Iikeys IIKEYS = new org.jooq.util.ingres.ingres.tables.Iikeys();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.Record> getRecordType() {
		return org.jooq.Record.class;
	}

	/**
	 * The column <code>$ingres.iikeys.constraint_name</code>.
	 */
	public static final org.jooq.TableField<org.jooq.Record, java.lang.String> CONSTRAINT_NAME = createField("constraint_name", org.jooq.impl.SQLDataType.CHAR.length(256).nullable(false).defaulted(true), IIKEYS, "");

	/**
	 * The column <code>$ingres.iikeys.schema_name</code>.
	 */
	public static final org.jooq.TableField<org.jooq.Record, java.lang.String> SCHEMA_NAME = createField("schema_name", org.jooq.impl.SQLDataType.CHAR.length(32).nullable(false).defaulted(true), IIKEYS, "");

	/**
	 * The column <code>$ingres.iikeys.table_name</code>.
	 */
	public static final org.jooq.TableField<org.jooq.Record, java.lang.String> TABLE_NAME = createField("table_name", org.jooq.impl.SQLDataType.CHAR.length(256).nullable(false).defaulted(true), IIKEYS, "");

	/**
	 * The column <code>$ingres.iikeys.column_name</code>.
	 */
	public static final org.jooq.TableField<org.jooq.Record, java.lang.String> COLUMN_NAME = createField("column_name", org.jooq.impl.SQLDataType.CHAR.length(256).nullable(false).defaulted(true), IIKEYS, "");

	/**
	 * The column <code>$ingres.iikeys.key_position</code>.
	 */
	public static final org.jooq.TableField<org.jooq.Record, java.lang.Short> KEY_POSITION = createField("key_position", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), IIKEYS, "");

	/**
	 * No further instances allowed
	 */
	private Iikeys() {
		this("iikeys", null);
	}

	private Iikeys(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased) {
		this(alias, aliased, null);
	}

	private Iikeys(java.lang.String alias, org.jooq.Table<org.jooq.Record> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.jooq.util.ingres.ingres.$ingres.$INGRES, aliased, parameters, "");
	}
}
