/**
 * This class is generated by jOOQ
 */
package org.jooq.util.postgres.pg_catalog.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.2"},
                            comments = "This class is generated by jOOQ")
public class PgTypeRecord extends org.jooq.impl.TableRecordImpl<org.jooq.util.postgres.pg_catalog.tables.records.PgTypeRecord> {

	private static final long serialVersionUID = -1594558076;

	/**
	 * An uncommented item
	 */
	public void setTypname(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPNAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypname() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPNAME);
	}

	/**
	 * An uncommented item
	 */
	public void setTypnamespace(java.lang.Long value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPNAMESPACE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Long getTypnamespace() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPNAMESPACE);
	}

	/**
	 * An uncommented item
	 */
	public void setTypowner(java.lang.Long value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPOWNER, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Long getTypowner() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPOWNER);
	}

	/**
	 * An uncommented item
	 */
	public void setTyplen(java.lang.Short value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPLEN, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Short getTyplen() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPLEN);
	}

	/**
	 * An uncommented item
	 */
	public void setTypbyval(java.lang.Boolean value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPBYVAL, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Boolean getTypbyval() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPBYVAL);
	}

	/**
	 * An uncommented item
	 */
	public void setTyptype(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPTYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTyptype() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPTYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setTypcategory(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPCATEGORY, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypcategory() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPCATEGORY);
	}

	/**
	 * An uncommented item
	 */
	public void setTypispreferred(java.lang.Boolean value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPISPREFERRED, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Boolean getTypispreferred() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPISPREFERRED);
	}

	/**
	 * An uncommented item
	 */
	public void setTypisdefined(java.lang.Boolean value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPISDEFINED, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Boolean getTypisdefined() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPISDEFINED);
	}

	/**
	 * An uncommented item
	 */
	public void setTypdelim(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPDELIM, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypdelim() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPDELIM);
	}

	/**
	 * An uncommented item
	 */
	public void setTyprelid(java.lang.Long value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPRELID, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Long getTyprelid() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPRELID);
	}

	/**
	 * An uncommented item
	 */
	public void setTypelem(java.lang.Long value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPELEM, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Long getTypelem() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPELEM);
	}

	/**
	 * An uncommented item
	 */
	public void setTyparray(java.lang.Long value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPARRAY, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Long getTyparray() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPARRAY);
	}

	/**
	 * An uncommented item
	 */
	public void setTypinput(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPINPUT, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypinput() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPINPUT);
	}

	/**
	 * An uncommented item
	 */
	public void setTypoutput(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPOUTPUT, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypoutput() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPOUTPUT);
	}

	/**
	 * An uncommented item
	 */
	public void setTypreceive(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPRECEIVE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypreceive() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPRECEIVE);
	}

	/**
	 * An uncommented item
	 */
	public void setTypsend(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPSEND, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypsend() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPSEND);
	}

	/**
	 * An uncommented item
	 */
	public void setTypmodin(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPMODIN, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypmodin() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPMODIN);
	}

	/**
	 * An uncommented item
	 */
	public void setTypmodout(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPMODOUT, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypmodout() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPMODOUT);
	}

	/**
	 * An uncommented item
	 */
	public void setTypanalyze(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPANALYZE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypanalyze() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPANALYZE);
	}

	/**
	 * An uncommented item
	 */
	public void setTypalign(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPALIGN, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypalign() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPALIGN);
	}

	/**
	 * An uncommented item
	 */
	public void setTypstorage(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPSTORAGE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypstorage() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPSTORAGE);
	}

	/**
	 * An uncommented item
	 */
	public void setTypnotnull(java.lang.Boolean value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPNOTNULL, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Boolean getTypnotnull() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPNOTNULL);
	}

	/**
	 * An uncommented item
	 */
	public void setTypbasetype(java.lang.Long value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPBASETYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Long getTypbasetype() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPBASETYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setTyptypmod(java.lang.Integer value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPTYPMOD, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getTyptypmod() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPTYPMOD);
	}

	/**
	 * An uncommented item
	 */
	public void setTypndims(java.lang.Integer value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPNDIMS, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getTypndims() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPNDIMS);
	}

	/**
	 * An uncommented item
	 */
	public void setTypdefaultbin(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPDEFAULTBIN, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypdefaultbin() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPDEFAULTBIN);
	}

	/**
	 * An uncommented item
	 */
	public void setTypdefault(java.lang.String value) {
		setValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPDEFAULT, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTypdefault() {
		return getValue(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE.TYPDEFAULT);
	}

	/**
	 * Create a detached PgTypeRecord
	 */
	public PgTypeRecord() {
		super(org.jooq.util.postgres.pg_catalog.tables.PgType.PG_TYPE);
	}
}
