/**
 * This class is generated by jOOQ
 */
package org.jooq.test.postgres.generatedclasses.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFTables5 extends Serializable {

	/**
	 * Getter for <code>public.f_tables5.v</code>.
	 */
	public Integer getV();

	/**
	 * Getter for <code>public.f_tables5.s</code>.
	 */
	public Integer getS();
}
