/**
 * This class is generated by jOOQ
 */
package org.jooq.test.postgres.generatedclasses.tables.interfaces;


import java.io.Serializable;
import java.sql.Date;

import org.jooq.test.postgres.generatedclasses.udt.interfaces.IUAddressType;


/**
 * An entity holding authors of books
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITAuthor extends Serializable {

	/**
	 * Getter for <code>public.t_author.id</code>. The author ID
	 */
	public Integer getId();

	/**
	 * Getter for <code>public.t_author.first_name</code>. The author's first name
	 */
	public String getFirstName();

	/**
	 * Getter for <code>public.t_author.last_name</code>. The author's last name
	 */
	public String getLastName();

	/**
	 * Getter for <code>public.t_author.date_of_birth</code>. The author's date of birth
	 */
	public Date getDateOfBirth();

	/**
	 * Getter for <code>public.t_author.year_of_birth</code>. The author's year of birth
	 */
	public Integer getYearOfBirth();

	/**
	 * Getter for <code>public.t_author.address</code>. The author's address
	 */
	public IUAddressType getAddress();
}
