/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle.generatedclasses.udt;

/**
 * This class is generated by jOOQ.
 */
public class UBookType extends org.jooq.impl.UDTImpl<org.jooq.test.oracle.generatedclasses.udt.records.UBookTypeRecord> {

	private static final long serialVersionUID = -1070806926;

	/**
	 * The singleton instance of U_BOOK_TYPE
	 */
	public static final org.jooq.test.oracle.generatedclasses.udt.UBookType U_BOOK_TYPE = new org.jooq.test.oracle.generatedclasses.udt.UBookType();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<org.jooq.test.oracle.generatedclasses.udt.records.UBookTypeRecord> __RECORD_TYPE = org.jooq.test.oracle.generatedclasses.udt.records.UBookTypeRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.test.oracle.generatedclasses.udt.records.UBookTypeRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final org.jooq.UDTField<org.jooq.test.oracle.generatedclasses.udt.records.UBookTypeRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, U_BOOK_TYPE);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.UDTField<org.jooq.test.oracle.generatedclasses.udt.records.UBookTypeRecord, java.lang.String> TITLE = createField("TITLE", org.jooq.impl.SQLDataType.VARCHAR, U_BOOK_TYPE);

	/**
	 * No further instances allowed
	 */
	private UBookType() {
		super("U_BOOK_TYPE", org.jooq.test.oracle.generatedclasses.Test.TEST);
	}
}
