/**
 * This class is generated by jOOQ
 */
package org.jooq.test.firebird.generatedclasses.tables.interfaces;


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.jooq.test.all.converters.Boolean_10;
import org.jooq.test.all.converters.Boolean_TF_LC;
import org.jooq.test.all.converters.Boolean_TF_UC;
import org.jooq.test.all.converters.Boolean_YES_NO_LC;
import org.jooq.test.all.converters.Boolean_YES_NO_UC;
import org.jooq.test.all.converters.Boolean_YN_LC;
import org.jooq.test.all.converters.Boolean_YN_UC;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "T_BOOLEANS")
public interface ITBooleans extends Serializable {

	/**
	 * Setter for <code>T_BOOLEANS.ID</code>.
	 */
	public void setId(Integer value);

	/**
	 * Getter for <code>T_BOOLEANS.ID</code>.
	 */
	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@NotNull
	public Integer getId();

	/**
	 * Setter for <code>T_BOOLEANS.ONE_ZERO</code>.
	 */
	public void setOneZero(Boolean_10 value);

	/**
	 * Getter for <code>T_BOOLEANS.ONE_ZERO</code>.
	 */
	@Column(name = "ONE_ZERO")
	public Boolean_10 getOneZero();

	/**
	 * Setter for <code>T_BOOLEANS.TRUE_FALSE_LC</code>.
	 */
	public void setTrueFalseLc(Boolean_TF_LC value);

	/**
	 * Getter for <code>T_BOOLEANS.TRUE_FALSE_LC</code>.
	 */
	@Column(name = "TRUE_FALSE_LC", length = 5)
	public Boolean_TF_LC getTrueFalseLc();

	/**
	 * Setter for <code>T_BOOLEANS.TRUE_FALSE_UC</code>.
	 */
	public void setTrueFalseUc(Boolean_TF_UC value);

	/**
	 * Getter for <code>T_BOOLEANS.TRUE_FALSE_UC</code>.
	 */
	@Column(name = "TRUE_FALSE_UC", length = 5)
	public Boolean_TF_UC getTrueFalseUc();

	/**
	 * Setter for <code>T_BOOLEANS.YES_NO_LC</code>.
	 */
	public void setYesNoLc(Boolean_YES_NO_LC value);

	/**
	 * Getter for <code>T_BOOLEANS.YES_NO_LC</code>.
	 */
	@Column(name = "YES_NO_LC", length = 3)
	public Boolean_YES_NO_LC getYesNoLc();

	/**
	 * Setter for <code>T_BOOLEANS.YES_NO_UC</code>.
	 */
	public void setYesNoUc(Boolean_YES_NO_UC value);

	/**
	 * Getter for <code>T_BOOLEANS.YES_NO_UC</code>.
	 */
	@Column(name = "YES_NO_UC", length = 3)
	public Boolean_YES_NO_UC getYesNoUc();

	/**
	 * Setter for <code>T_BOOLEANS.Y_N_LC</code>.
	 */
	public void setYNLc(Boolean_YN_LC value);

	/**
	 * Getter for <code>T_BOOLEANS.Y_N_LC</code>.
	 */
	@Column(name = "Y_N_LC", length = 1)
	public Boolean_YN_LC getYNLc();

	/**
	 * Setter for <code>T_BOOLEANS.Y_N_UC</code>.
	 */
	public void setYNUc(Boolean_YN_UC value);

	/**
	 * Getter for <code>T_BOOLEANS.Y_N_UC</code>.
	 */
	@Column(name = "Y_N_UC", length = 1)
	public Boolean_YN_UC getYNUc();

	/**
	 * Setter for <code>T_BOOLEANS.VC_BOOLEAN</code>.
	 */
	public void setVcBoolean(Boolean value);

	/**
	 * Getter for <code>T_BOOLEANS.VC_BOOLEAN</code>.
	 */
	@Column(name = "VC_BOOLEAN")
	public Boolean getVcBoolean();

	/**
	 * Setter for <code>T_BOOLEANS.C_BOOLEAN</code>.
	 */
	public void setCBoolean(Boolean value);

	/**
	 * Getter for <code>T_BOOLEANS.C_BOOLEAN</code>.
	 */
	@Column(name = "C_BOOLEAN")
	public Boolean getCBoolean();

	/**
	 * Setter for <code>T_BOOLEANS.N_BOOLEAN</code>.
	 */
	public void setNBoolean(Boolean value);

	/**
	 * Getter for <code>T_BOOLEANS.N_BOOLEAN</code>.
	 */
	@Column(name = "N_BOOLEAN")
	public Boolean getNBoolean();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ITBooleans
	 */
	public void from(org.jooq.test.firebird.generatedclasses.tables.interfaces.ITBooleans from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ITBooleans
	 */
	public <E extends org.jooq.test.firebird.generatedclasses.tables.interfaces.ITBooleans> E into(E into);
}
