/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle3.generatedclasses.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.test.oracle3.generatedclasses.DefaultSchema;
import org.jooq.test.oracle3.generatedclasses.udt.records.U_NUMBER_LONG_ARRAY;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class P_ARRAYS2 extends AbstractRoutine<java.lang.Void> implements Cloneable {

	private static final long serialVersionUID = 401876803;

	/**
	 * The parameter <code>P_ARRAYS2.IN_ARRAY</code>.
	 */
	public static final Parameter<U_NUMBER_LONG_ARRAY> IN_ARRAY = createParameter("IN_ARRAY", org.jooq.impl.SQLDataType.BIGINT.asArrayDataType(org.jooq.test.oracle3.generatedclasses.udt.records.U_NUMBER_LONG_ARRAY.class), false);

	/**
	 * The parameter <code>P_ARRAYS2.OUT_ARRAY</code>.
	 */
	public static final Parameter<U_NUMBER_LONG_ARRAY> OUT_ARRAY = createParameter("OUT_ARRAY", org.jooq.impl.SQLDataType.BIGINT.asArrayDataType(org.jooq.test.oracle3.generatedclasses.udt.records.U_NUMBER_LONG_ARRAY.class), false);

	/**
	 * Create a new routine call instance
	 */
	public P_ARRAYS2() {
		super("P_ARRAYS2", DefaultSchema.DEFAULT_SCHEMA);

		addInParameter(IN_ARRAY);
		addOutParameter(OUT_ARRAY);
	}

	/**
	 * Set the <code>IN_ARRAY</code> parameter IN value to the routine
	 */
	public void setIN_ARRAY(U_NUMBER_LONG_ARRAY value) {
		setValue(IN_ARRAY, value);
	}

	/**
	 * Get the <code>OUT_ARRAY</code> parameter OUT value from the routine
	 */
	public U_NUMBER_LONG_ARRAY getOUT_ARRAY() {
		return getValue(OUT_ARRAY);
	}
}
