/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle5.generatedclasses.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VAuthorRecord extends org.jooq.impl.TableRecordImpl<org.jooq.test.oracle5.generatedclasses.tables.records.VAuthorRecord> implements org.jooq.Record6<java.math.BigDecimal, java.lang.String, java.lang.String, java.time.LocalDate, java.math.BigDecimal, org.jooq.test.oracle5.generatedclasses.udt.records.UAddressTypeRecord> {

	private static final long serialVersionUID = -1330613992;

	/**
	 * Setter for <code>TEST.V_AUTHOR.ID</code>.
	 */
	public void setId(java.math.BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>TEST.V_AUTHOR.ID</code>.
	 */
	public java.math.BigDecimal getId() {
		return (java.math.BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>TEST.V_AUTHOR.FIRST_NAME</code>.
	 */
	public void setFirstName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>TEST.V_AUTHOR.FIRST_NAME</code>.
	 */
	public java.lang.String getFirstName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>TEST.V_AUTHOR.LAST_NAME</code>.
	 */
	public void setLastName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>TEST.V_AUTHOR.LAST_NAME</code>.
	 */
	public java.lang.String getLastName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>TEST.V_AUTHOR.DATE_OF_BIRTH</code>.
	 */
	public void setDateOfBirth(java.time.LocalDate value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>TEST.V_AUTHOR.DATE_OF_BIRTH</code>.
	 */
	public java.time.LocalDate getDateOfBirth() {
		return (java.time.LocalDate) getValue(3);
	}

	/**
	 * Setter for <code>TEST.V_AUTHOR.YEAR_OF_BIRTH</code>.
	 */
	public void setYearOfBirth(java.math.BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>TEST.V_AUTHOR.YEAR_OF_BIRTH</code>.
	 */
	public java.math.BigDecimal getYearOfBirth() {
		return (java.math.BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>TEST.V_AUTHOR.ADDRESS</code>.
	 */
	public void setAddress(org.jooq.test.oracle5.generatedclasses.udt.records.UAddressTypeRecord value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>TEST.V_AUTHOR.ADDRESS</code>.
	 */
	public org.jooq.test.oracle5.generatedclasses.udt.records.UAddressTypeRecord getAddress() {
		return (org.jooq.test.oracle5.generatedclasses.udt.records.UAddressTypeRecord) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.math.BigDecimal, java.lang.String, java.lang.String, java.time.LocalDate, java.math.BigDecimal, org.jooq.test.oracle5.generatedclasses.udt.records.UAddressTypeRecord> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.math.BigDecimal, java.lang.String, java.lang.String, java.time.LocalDate, java.math.BigDecimal, org.jooq.test.oracle5.generatedclasses.udt.records.UAddressTypeRecord> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field1() {
		return org.jooq.test.oracle5.generatedclasses.tables.VAuthor.V_AUTHOR.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.jooq.test.oracle5.generatedclasses.tables.VAuthor.V_AUTHOR.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.jooq.test.oracle5.generatedclasses.tables.VAuthor.V_AUTHOR.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.time.LocalDate> field4() {
		return org.jooq.test.oracle5.generatedclasses.tables.VAuthor.V_AUTHOR.DATE_OF_BIRTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field5() {
		return org.jooq.test.oracle5.generatedclasses.tables.VAuthor.V_AUTHOR.YEAR_OF_BIRTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.test.oracle5.generatedclasses.udt.records.UAddressTypeRecord> field6() {
		return org.jooq.test.oracle5.generatedclasses.tables.VAuthor.V_AUTHOR.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.time.LocalDate value4() {
		return getDateOfBirth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value5() {
		return getYearOfBirth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.test.oracle5.generatedclasses.udt.records.UAddressTypeRecord value6() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VAuthorRecord value1(java.math.BigDecimal value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VAuthorRecord value2(java.lang.String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VAuthorRecord value3(java.lang.String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VAuthorRecord value4(java.time.LocalDate value) {
		setDateOfBirth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VAuthorRecord value5(java.math.BigDecimal value) {
		setYearOfBirth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VAuthorRecord value6(org.jooq.test.oracle5.generatedclasses.udt.records.UAddressTypeRecord value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VAuthorRecord values(java.math.BigDecimal value1, java.lang.String value2, java.lang.String value3, java.time.LocalDate value4, java.math.BigDecimal value5, org.jooq.test.oracle5.generatedclasses.udt.records.UAddressTypeRecord value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VAuthorRecord
	 */
	public VAuthorRecord() {
		super(org.jooq.test.oracle5.generatedclasses.tables.VAuthor.V_AUTHOR);
	}

	/**
	 * Create a detached, initialised VAuthorRecord
	 */
	public VAuthorRecord(java.math.BigDecimal id, java.lang.String firstName, java.lang.String lastName, java.time.LocalDate dateOfBirth, java.math.BigDecimal yearOfBirth, org.jooq.test.oracle5.generatedclasses.udt.records.UAddressTypeRecord address) {
		super(org.jooq.test.oracle5.generatedclasses.tables.VAuthor.V_AUTHOR);

		setValue(0, id);
		setValue(1, firstName);
		setValue(2, lastName);
		setValue(3, dateOfBirth);
		setValue(4, yearOfBirth);
		setValue(5, address);
	}
}
