/**
 * This class is generated by jOOQ
 */
package org.jooq.test.jdbcoracle.generatedclasses.test.tables;


import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.test.jdbcoracle.generatedclasses.test.Keys;
import org.jooq.test.jdbcoracle.generatedclasses.test.Test;
import org.jooq.test.jdbcoracle.generatedclasses.test.tables.records.T_639NumbersTableRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_639NumbersTable extends TableImpl<T_639NumbersTableRecord> {

	private static final long serialVersionUID = 787807867;

	/**
	 * The reference instance of <code>TEST.T_639_NUMBERS_TABLE</code>
	 */
	public static final T_639NumbersTable T_639_NUMBERS_TABLE = new T_639NumbersTable();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<T_639NumbersTableRecord> getRecordType() {
		return T_639NumbersTableRecord.class;
	}

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.ID</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, T_639_NUMBERS_TABLE, "");

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.BYTE</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, Byte> BYTE = createField("BYTE", org.jooq.impl.SQLDataType.TINYINT, T_639_NUMBERS_TABLE, "");

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.SHORT</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, Short> SHORT = createField("SHORT", org.jooq.impl.SQLDataType.SMALLINT, T_639_NUMBERS_TABLE, "");

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.INTEGER</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, Integer> INTEGER = createField("INTEGER", org.jooq.impl.SQLDataType.INTEGER, T_639_NUMBERS_TABLE, "");

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.LONG</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, Long> LONG = createField("LONG", org.jooq.impl.SQLDataType.BIGINT, T_639_NUMBERS_TABLE, "");

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.BYTE_DECIMAL</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, Byte> BYTE_DECIMAL = createField("BYTE_DECIMAL", org.jooq.impl.SQLDataType.TINYINT, T_639_NUMBERS_TABLE, "");

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.SHORT_DECIMAL</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, Short> SHORT_DECIMAL = createField("SHORT_DECIMAL", org.jooq.impl.SQLDataType.SMALLINT, T_639_NUMBERS_TABLE, "");

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.INTEGER_DECIMAL</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, Integer> INTEGER_DECIMAL = createField("INTEGER_DECIMAL", org.jooq.impl.SQLDataType.INTEGER, T_639_NUMBERS_TABLE, "");

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.LONG_DECIMAL</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, Long> LONG_DECIMAL = createField("LONG_DECIMAL", org.jooq.impl.SQLDataType.BIGINT, T_639_NUMBERS_TABLE, "");

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.BIG_INTEGER</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, BigInteger> BIG_INTEGER = createField("BIG_INTEGER", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(22), T_639_NUMBERS_TABLE, "");

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.BIG_DECIMAL</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, BigDecimal> BIG_DECIMAL = createField("BIG_DECIMAL", org.jooq.impl.SQLDataType.NUMERIC.precision(22, 5), T_639_NUMBERS_TABLE, "");

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.FLOAT</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, Double> FLOAT = createField("FLOAT", org.jooq.impl.SQLDataType.DOUBLE, T_639_NUMBERS_TABLE, "");

	/**
	 * The column <code>TEST.T_639_NUMBERS_TABLE.REAL</code>.
	 */
	public static final TableField<T_639NumbersTableRecord, Double> REAL = createField("REAL", org.jooq.impl.SQLDataType.DOUBLE, T_639_NUMBERS_TABLE, "");

	/**
	 * No further instances allowed
	 */
	private T_639NumbersTable() {
		this("T_639_NUMBERS_TABLE", null);
	}

	private T_639NumbersTable(String alias, Table<T_639NumbersTableRecord> aliased) {
		this(alias, aliased, null);
	}

	private T_639NumbersTable(String alias, Table<T_639NumbersTableRecord> aliased, Field<?>[] parameters) {
		super(alias, Test.TEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<T_639NumbersTableRecord> getPrimaryKey() {
		return Keys.PK_T_639_NUMBERS_TABLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<T_639NumbersTableRecord>> getKeys() {
		return Arrays.<UniqueKey<T_639NumbersTableRecord>>asList(Keys.PK_T_639_NUMBERS_TABLE);
	}
}
