/**
 * This class is generated by jOOQ
 */
package org.jooq.test.hsqldb.generatedclasses.tables;


import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.jooq.test.hsqldb.generatedclasses.Public;
import org.jooq.test.hsqldb.generatedclasses.tables.records.SystemRecord;


/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class System extends TableImpl<SystemRecord> {

	private static final long serialVersionUID = -1554411886;

	/**
	 * The reference instance of <code>PUBLIC.SYSTEM</code>
	 */
	public static final System SYSTEM = new System();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<SystemRecord> getRecordType() {
		return SystemRecord.class;
	}

	/**
	 * The column <code>PUBLIC.SYSTEM.ID</code>.
	 */
	public final TableField<SystemRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>PUBLIC.SYSTEM</code> table reference
	 */
	public System() {
		this("SYSTEM", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.SYSTEM</code> table reference
	 */
	public System(java.lang.String alias) {
		this(alias, SYSTEM);
	}

	private System(java.lang.String alias, Table<SystemRecord> aliased) {
		this(alias, aliased, null);
	}

	private System(java.lang.String alias, Table<SystemRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public System as(java.lang.String alias) {
		return new System(alias, this);
	}

	/**
	 * Rename this table
	 */
	public System rename(java.lang.String name) {
		return new System(name, null);
	}
}
