/**
 * This class is generated by jOOQ
 */
package org.jooq.test.h2.generatedclasses.public_.tables.daos;


import java.math.BigDecimal;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.test.h2.generatedclasses.public_.tables.Accounts;
import org.jooq.test.h2.generatedclasses.public_.tables.records.AccountsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountsDao extends DAOImpl<AccountsRecord, org.jooq.test.h2.generatedclasses.public_.tables.pojos.Accounts, Integer> {

	/**
	 * Create a new AccountsDao without any configuration
	 */
	public AccountsDao() {
		super(Accounts.ACCOUNTS, org.jooq.test.h2.generatedclasses.public_.tables.pojos.Accounts.class);
	}

	/**
	 * Create a new AccountsDao with an attached configuration
	 */
	public AccountsDao(Configuration configuration) {
		super(Accounts.ACCOUNTS, org.jooq.test.h2.generatedclasses.public_.tables.pojos.Accounts.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.jooq.test.h2.generatedclasses.public_.tables.pojos.Accounts object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>ID IN (values)</code>
	 */
	public List<org.jooq.test.h2.generatedclasses.public_.tables.pojos.Accounts> fetchById(Integer... values) {
		return fetch(Accounts.ACCOUNTS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>ID = value</code>
	 */
	public org.jooq.test.h2.generatedclasses.public_.tables.pojos.Accounts fetchOneById(Integer value) {
		return fetchOne(Accounts.ACCOUNTS.ID, value);
	}

	/**
	 * Fetch records that have <code>ACCOUNT_OWNER IN (values)</code>
	 */
	public List<org.jooq.test.h2.generatedclasses.public_.tables.pojos.Accounts> fetchByAccountOwner(String... values) {
		return fetch(Accounts.ACCOUNTS.ACCOUNT_OWNER, values);
	}

	/**
	 * Fetch records that have <code>ACCOUNT_NAME IN (values)</code>
	 */
	public List<org.jooq.test.h2.generatedclasses.public_.tables.pojos.Accounts> fetchByAccountName(String... values) {
		return fetch(Accounts.ACCOUNTS.ACCOUNT_NAME, values);
	}

	/**
	 * Fetch records that have <code>AMOUNT IN (values)</code>
	 */
	public List<org.jooq.test.h2.generatedclasses.public_.tables.pojos.Accounts> fetchByAmount(BigDecimal... values) {
		return fetch(Accounts.ACCOUNTS.AMOUNT, values);
	}
}
