/**
 * This class is generated by jOOQ
 */
package org.jooq.test.ingres.generatedclasses.tables.records;

/**
 * This class is generated by jOOQ.
 */
public class TDatesRecord extends org.jooq.impl.UpdatableRecordImpl<org.jooq.test.ingres.generatedclasses.tables.records.TDatesRecord> {

	private static final long serialVersionUID = 1846271268;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.jooq.test.ingres.generatedclasses.tables.TDates.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.jooq.test.ingres.generatedclasses.tables.TDates.ID);
	}

	/**
	 * An uncommented item
	 */
	public void setD(java.sql.Date value) {
		setValue(org.jooq.test.ingres.generatedclasses.tables.TDates.D, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Date getD() {
		return getValue(org.jooq.test.ingres.generatedclasses.tables.TDates.D);
	}

	/**
	 * An uncommented item
	 */
	public void setT(java.sql.Time value) {
		setValue(org.jooq.test.ingres.generatedclasses.tables.TDates.T, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Time getT() {
		return getValue(org.jooq.test.ingres.generatedclasses.tables.TDates.T);
	}

	/**
	 * An uncommented item
	 */
	public void setTs(java.sql.Timestamp value) {
		setValue(org.jooq.test.ingres.generatedclasses.tables.TDates.TS, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getTs() {
		return getValue(org.jooq.test.ingres.generatedclasses.tables.TDates.TS);
	}

	/**
	 * An uncommented item
	 */
	public void setDInt(java.lang.Integer value) {
		setValue(org.jooq.test.ingres.generatedclasses.tables.TDates.D_INT, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getDInt() {
		return getValue(org.jooq.test.ingres.generatedclasses.tables.TDates.D_INT);
	}

	/**
	 * An uncommented item
	 */
	public void setTsBigint(java.lang.Long value) {
		setValue(org.jooq.test.ingres.generatedclasses.tables.TDates.TS_BIGINT, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Long getTsBigint() {
		return getValue(org.jooq.test.ingres.generatedclasses.tables.TDates.TS_BIGINT);
	}

	/**
	 * Create a detached TDatesRecord
	 */
	public TDatesRecord() {
		super(org.jooq.test.ingres.generatedclasses.tables.TDates.T_DATES);
	}
}
