/**
 * This class is generated by jOOQ
 */
package org.jooq.test.db2.generatedclasses.routines;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings("all")
public class PCreateAuthor extends org.jooq.impl.AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -1688827384;

	/**
	 * Create a new routine call instance
	 */
	public PCreateAuthor() {
		super("P_CREATE_AUTHOR", org.jooq.test.db2.generatedclasses.Test.TEST);
	}
}
