/**
 * This class is generated by jOOQ
 */
package org.jooq.test.postgres.generatedclasses.udt.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UAddressTypeRecord extends org.jooq.impl.UDTRecordImpl<org.jooq.test.postgres.generatedclasses.udt.records.UAddressTypeRecord> implements org.jooq.Record7<org.jooq.test.postgres.generatedclasses.udt.records.UStreetTypeRecord, java.lang.String, java.lang.String, org.jooq.test.postgres.generatedclasses.enums.UCountry, java.sql.Date, java.lang.Integer, byte[]>, org.jooq.test.postgres.generatedclasses.udt.interfaces.IUAddressType {

	private static final long serialVersionUID = -1545223750;

	/**
	 * Setter for <code>public.u_address_type.street</code>.
	 */
	public UAddressTypeRecord setStreet(org.jooq.test.postgres.generatedclasses.udt.records.UStreetTypeRecord value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.u_address_type.street</code>.
	 */
	@Override
	public org.jooq.test.postgres.generatedclasses.udt.records.UStreetTypeRecord getStreet() {
		return (org.jooq.test.postgres.generatedclasses.udt.records.UStreetTypeRecord) getValue(0);
	}

	/**
	 * Setter for <code>public.u_address_type.zip</code>.
	 */
	public UAddressTypeRecord setZip(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.u_address_type.zip</code>.
	 */
	@Override
	public java.lang.String getZip() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.u_address_type.city</code>.
	 */
	public UAddressTypeRecord setCity(java.lang.String value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.u_address_type.city</code>.
	 */
	@Override
	public java.lang.String getCity() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.u_address_type.country</code>.
	 */
	public UAddressTypeRecord setCountry(org.jooq.test.postgres.generatedclasses.enums.UCountry value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.u_address_type.country</code>.
	 */
	@Override
	public org.jooq.test.postgres.generatedclasses.enums.UCountry getCountry() {
		return (org.jooq.test.postgres.generatedclasses.enums.UCountry) getValue(3);
	}

	/**
	 * Setter for <code>public.u_address_type.since</code>.
	 */
	public UAddressTypeRecord setSince(java.sql.Date value) {
		setValue(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.u_address_type.since</code>.
	 */
	@Override
	public java.sql.Date getSince() {
		return (java.sql.Date) getValue(4);
	}

	/**
	 * Setter for <code>public.u_address_type.code</code>.
	 */
	public UAddressTypeRecord setCode(java.lang.Integer value) {
		setValue(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.u_address_type.code</code>.
	 */
	@Override
	public java.lang.Integer getCode() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.u_address_type.f_1323</code>.
	 */
	public UAddressTypeRecord setF_1323(byte[] value) {
		setValue(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.u_address_type.f_1323</code>.
	 */
	@Override
	public byte[] getF_1323() {
		return (byte[]) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<org.jooq.test.postgres.generatedclasses.udt.records.UStreetTypeRecord, java.lang.String, java.lang.String, org.jooq.test.postgres.generatedclasses.enums.UCountry, java.sql.Date, java.lang.Integer, byte[]> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<org.jooq.test.postgres.generatedclasses.udt.records.UStreetTypeRecord, java.lang.String, java.lang.String, org.jooq.test.postgres.generatedclasses.enums.UCountry, java.sql.Date, java.lang.Integer, byte[]> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.test.postgres.generatedclasses.udt.records.UStreetTypeRecord> field1() {
		return org.jooq.test.postgres.generatedclasses.udt.UAddressType.STREET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.jooq.test.postgres.generatedclasses.udt.UAddressType.ZIP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.jooq.test.postgres.generatedclasses.udt.UAddressType.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.test.postgres.generatedclasses.enums.UCountry> field4() {
		return org.jooq.test.postgres.generatedclasses.udt.UAddressType.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field5() {
		return org.jooq.test.postgres.generatedclasses.udt.UAddressType.SINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return org.jooq.test.postgres.generatedclasses.udt.UAddressType.CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field7() {
		return org.jooq.test.postgres.generatedclasses.udt.UAddressType.F_1323;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.test.postgres.generatedclasses.udt.records.UStreetTypeRecord value1() {
		return getStreet();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getZip();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.test.postgres.generatedclasses.enums.UCountry value4() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value5() {
		return getSince();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value7() {
		return getF_1323();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UAddressTypeRecord value1(org.jooq.test.postgres.generatedclasses.udt.records.UStreetTypeRecord value) {
		setStreet(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UAddressTypeRecord value2(java.lang.String value) {
		setZip(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UAddressTypeRecord value3(java.lang.String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UAddressTypeRecord value4(org.jooq.test.postgres.generatedclasses.enums.UCountry value) {
		setCountry(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UAddressTypeRecord value5(java.sql.Date value) {
		setSince(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UAddressTypeRecord value6(java.lang.Integer value) {
		setCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UAddressTypeRecord value7(byte[] value) {
		setF_1323(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UAddressTypeRecord values(org.jooq.test.postgres.generatedclasses.udt.records.UStreetTypeRecord value1, java.lang.String value2, java.lang.String value3, org.jooq.test.postgres.generatedclasses.enums.UCountry value4, java.sql.Date value5, java.lang.Integer value6, byte[] value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UAddressTypeRecord
	 */
	public UAddressTypeRecord() {
		super(org.jooq.test.postgres.generatedclasses.udt.UAddressType.U_ADDRESS_TYPE);
	}

	/**
	 * Create a detached, initialised UAddressTypeRecord
	 */
	public UAddressTypeRecord(org.jooq.test.postgres.generatedclasses.udt.records.UStreetTypeRecord street, java.lang.String zip, java.lang.String city, org.jooq.test.postgres.generatedclasses.enums.UCountry country, java.sql.Date since, java.lang.Integer code, byte[] f_1323) {
		super(org.jooq.test.postgres.generatedclasses.udt.UAddressType.U_ADDRESS_TYPE);

		setValue(0, street);
		setValue(1, zip);
		setValue(2, city);
		setValue(3, country);
		setValue(4, since);
		setValue(5, code);
		setValue(6, f_1323);
	}
}
