/**
 * This class is generated by jOOQ
 */
package org.jooq.test.postgres.generatedclasses.udt.records;


import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UDTRecordImpl;
import org.jooq.test.postgres.generatedclasses.udt.UStreetType;
import org.jooq.test.postgres.generatedclasses.udt.interfaces.IUStreetType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UStreetTypeRecord extends UDTRecordImpl<UStreetTypeRecord> implements Record4<String, String, Integer[], byte[]>, IUStreetType {

	private static final long serialVersionUID = -363281025;

	/**
	 * Setter for <code>public.u_street_type.street</code>.
	 */
	public UStreetTypeRecord setStreet(String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.u_street_type.street</code>.
	 */
	@Override
	public String getStreet() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.u_street_type.no</code>.
	 */
	public UStreetTypeRecord setNo(String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.u_street_type.no</code>.
	 */
	@Override
	public String getNo() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.u_street_type.floors</code>.
	 */
	public UStreetTypeRecord setFloors(Integer[] value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.u_street_type.floors</code>.
	 */
	@Override
	public Integer[] getFloors() {
		return (Integer[]) getValue(2);
	}

	/**
	 * Setter for <code>public.u_street_type.f_1323</code>.
	 */
	public UStreetTypeRecord setF_1323(byte[] value) {
		setValue(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.u_street_type.f_1323</code>.
	 */
	@Override
	public byte[] getF_1323() {
		return (byte[]) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, String, Integer[], byte[]> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<String, String, Integer[], byte[]> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return UStreetType.STREET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return UStreetType.NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer[]> field3() {
		return UStreetType.FLOORS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<byte[]> field4() {
		return UStreetType.F_1323;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getStreet();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer[] value3() {
		return getFloors();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value4() {
		return getF_1323();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UStreetTypeRecord value1(String value) {
		setStreet(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UStreetTypeRecord value2(String value) {
		setNo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UStreetTypeRecord value3(Integer[] value) {
		setFloors(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UStreetTypeRecord value4(byte[] value) {
		setF_1323(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UStreetTypeRecord values(String value1, String value2, Integer[] value3, byte[] value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UStreetTypeRecord
	 */
	public UStreetTypeRecord() {
		super(UStreetType.U_STREET_TYPE);
	}

	/**
	 * Create a detached, initialised UStreetTypeRecord
	 */
	public UStreetTypeRecord(String street, String no, Integer[] floors, byte[] f_1323) {
		super(UStreetType.U_STREET_TYPE);

		setValue(0, street);
		setValue(1, no);
		setValue(2, floors);
		setValue(3, f_1323);
	}
}
