/**
 * This class is generated by jOOQ
 */
package org.jooq.test.mysql.generatedclasses.tables;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public class VBook extends org.jooq.impl.TableImpl<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord> {

	private static final long serialVersionUID = -1152107376;

	/**
	 * The singleton instance of v_book
	 */
	public static final org.jooq.test.mysql.generatedclasses.tables.VBook V_BOOK = new org.jooq.test.mysql.generatedclasses.tables.VBook();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord> __RECORD_TYPE = org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * The book ID
	 */
	public static final org.jooq.TableField<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.Integer> ID = new org.jooq.impl.TableFieldImpl<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.Integer>("ID", org.jooq.impl.SQLDataType.INTEGER, V_BOOK);

	/**
	 * The author ID in entity 'author'
	 */
	public static final org.jooq.TableField<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.Integer> AUTHOR_ID = new org.jooq.impl.TableFieldImpl<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.Integer>("AUTHOR_ID", org.jooq.impl.SQLDataType.INTEGER, V_BOOK);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.Integer> CO_AUTHOR_ID = new org.jooq.impl.TableFieldImpl<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.Integer>("co_author_id", org.jooq.impl.SQLDataType.INTEGER, V_BOOK);

	/**
	 * Some more details about the book
	 */
	public static final org.jooq.TableField<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.Integer> DETAILS_ID = new org.jooq.impl.TableFieldImpl<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.Integer>("DETAILS_ID", org.jooq.impl.SQLDataType.INTEGER, V_BOOK);

	/**
	 * The book's title
	 */
	public static final org.jooq.TableField<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.String> TITLE = new org.jooq.impl.TableFieldImpl<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.String>("TITLE", org.jooq.impl.SQLDataType.CLOB, V_BOOK);

	/**
	 * The year the book was published in
	 */
	public static final org.jooq.TableField<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.Integer> PUBLISHED_IN = new org.jooq.impl.TableFieldImpl<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.Integer>("PUBLISHED_IN", org.jooq.impl.SQLDataType.INTEGER, V_BOOK);

	/**
	 * The language of the book
	 */
	public static final org.jooq.TableField<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.Integer> LANGUAGE_ID = new org.jooq.impl.TableFieldImpl<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.Integer>("LANGUAGE_ID", org.jooq.impl.SQLDataType.INTEGER, V_BOOK);

	/**
	 * Some textual content of the book
	 */
	public static final org.jooq.TableField<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.String> CONTENT_TEXT = new org.jooq.impl.TableFieldImpl<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, java.lang.String>("CONTENT_TEXT", org.jooq.impl.SQLDataType.CLOB, V_BOOK);

	/**
	 * Some binary content of the book
	 */
	public static final org.jooq.TableField<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, byte[]> CONTENT_PDF = new org.jooq.impl.TableFieldImpl<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, byte[]>("CONTENT_PDF", org.jooq.impl.SQLDataType.BLOB, V_BOOK);

	/**
	 * The book's stock status
	 */
	public static final org.jooq.TableField<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, org.jooq.test.mysql.generatedclasses.enums.VBookStatus> STATUS = new org.jooq.impl.TableFieldImpl<org.jooq.test.mysql.generatedclasses.tables.records.VBookRecord, org.jooq.test.mysql.generatedclasses.enums.VBookStatus>("STATUS", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(org.jooq.test.mysql.generatedclasses.enums.VBookStatus.class), V_BOOK);

	/**
	 * No further instances allowed
	 */
	private VBook() {
		super("v_book", org.jooq.test.mysql.generatedclasses.Test.TEST);
	}
}
