/**
 * This class is generated by jOOQ
 */
package org.jooq.test.oracle.generatedclasses.test.udt.records;

/**
 * This class is generated by jOOQ.
 */
public class UAddressTableRecord extends org.jooq.impl.ArrayRecordImpl<org.jooq.test.oracle.generatedclasses.test.udt.records.UAddressTypeRecord> {

	private static final long serialVersionUID = -1512459535;

	public UAddressTableRecord(org.jooq.Configuration configuration) {
		super(org.jooq.test.oracle.generatedclasses.test.Test.TEST, "U_ADDRESS_TABLE", org.jooq.test.oracle.generatedclasses.test.udt.UAddressType.U_ADDRESS_TYPE.getDataType(), configuration);
	}

	public UAddressTableRecord(org.jooq.Configuration configuration, org.jooq.test.oracle.generatedclasses.test.udt.records.UAddressTypeRecord... array) {
		this(configuration);
		set(array);
	}

	public UAddressTableRecord(org.jooq.Configuration configuration, java.util.List<? extends org.jooq.test.oracle.generatedclasses.test.udt.records.UAddressTypeRecord> list) {
		this(configuration);
		setList(list);
	}
}
