DROP TABLE MULTI_SCHEMA.T_BOOK_SALE/

CREATE TABLE MULTI_SCHEMA.T_BOOK_SALE (
  ID NUMBER(7) NOT NULL,
  BOOK_ID NUMBER(7) NOT NULL,
  BOOK_STORE_NAME VARCHAR2(400) NOT NULL,
  SOLD_AT DATE NOT NULL,
  SOLD_FOR NUMBER(10, 2) NOT NULL,

  CONSTRAINT pk_t_book_sale PRIMARY KEY (ID),
  CONSTRAINT fk_t_book_to_book_store FOREIGN KEY (BOOK_ID, BOOK_STORE_NAME) REFERENCES TEST.T_BOOK_TO_BOOK_STORE(BOOK_ID, BOOK_STORE_NAME) ON DELETE CASCADE
)
/
