/**
 * This class is generated by jOOQ
 */
package org.jooq.test.firebird.generatedclasses.enums;

/**
 * This class is generated by jOOQ.
 */
public enum T_658_12 implements org.jooq.MasterDataType<java.lang.String> {

	/**
	 * A  
	 */
	A__("A  ", "A  "),

	/**
	 * B  
	 */
	B__("B  ", "B  "),

	/**
	 * C  
	 */
	C__("C  ", "C  "),
	;

	private final java.lang.String id;
	private final java.lang.String cd;

	private T_658_12(java.lang.String id, java.lang.String cd) {
		this.id = id;
		this.cd = cd;
	}

	@Override
	public java.lang.String getPrimaryKey() {
		return id;
	}

	/**
	 * The table column <code>T_658_12.ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final java.lang.String getId() {
		return id;
	}

	/**
	 * The table column <code>T_658_12.CD</code>
	 */
	public final java.lang.String getCd() {
		return cd;
	}
}
