/**
 * This class is generated by jOOQ
 */
package org.jooq.examples.sqlserver.adventureworks.humanresources.routines;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class uspUpdateEmployeeLogin extends org.jooq.impl.AbstractRoutine<java.lang.Void> {

	private static final long serialVersionUID = -982372637;

	/**
	 * The parameter <code>HumanResources.uspUpdateEmployeeLogin.BusinessEntityID</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.Integer> BusinessEntityID = createParameter("BusinessEntityID", org.jooq.impl.SQLDataType.INTEGER);

	/**
	 * The parameter <code>HumanResources.uspUpdateEmployeeLogin.OrganizationNode</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.Object> OrganizationNode = createParameter("OrganizationNode", org.jooq.impl.DefaultDataType.getDefaultDataType("hierarchyid"));

	/**
	 * The parameter <code>HumanResources.uspUpdateEmployeeLogin.LoginID</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.String> LoginID = createParameter("LoginID", org.jooq.impl.SQLDataType.NVARCHAR.length(256));

	/**
	 * The parameter <code>HumanResources.uspUpdateEmployeeLogin.JobTitle</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.String> JobTitle = createParameter("JobTitle", org.jooq.impl.SQLDataType.NVARCHAR.length(50));

	/**
	 * The parameter <code>HumanResources.uspUpdateEmployeeLogin.HireDate</code>. 
	 */
	public static final org.jooq.Parameter<java.sql.Timestamp> HireDate = createParameter("HireDate", org.jooq.impl.SQLDataType.TIMESTAMP);

	/**
	 * The parameter <code>HumanResources.uspUpdateEmployeeLogin.CurrentFlag</code>. 
	 */
	public static final org.jooq.Parameter<java.lang.Boolean> CurrentFlag = createParameter("CurrentFlag", org.jooq.impl.SQLDataType.BIT);

	/**
	 * Create a new routine call instance
	 */
	public uspUpdateEmployeeLogin() {
		super("uspUpdateEmployeeLogin", org.jooq.examples.sqlserver.adventureworks.humanresources.HumanResources.HumanResources);

		addInParameter(BusinessEntityID);
		addInParameter(OrganizationNode);
		addInParameter(LoginID);
		addInParameter(JobTitle);
		addInParameter(HireDate);
		addInParameter(CurrentFlag);
	}

	/**
	 * Set the <code>BusinessEntityID</code> parameter IN value to the routine
	 */
	public void setBusinessEntityID(java.lang.Integer value) {
		setValue(org.jooq.examples.sqlserver.adventureworks.humanresources.routines.uspUpdateEmployeeLogin.BusinessEntityID, value);
	}

	/**
	 * Set the <code>OrganizationNode</code> parameter IN value to the routine
	 */
	public void setOrganizationNode(java.lang.Object value) {
		setValue(org.jooq.examples.sqlserver.adventureworks.humanresources.routines.uspUpdateEmployeeLogin.OrganizationNode, value);
	}

	/**
	 * Set the <code>LoginID</code> parameter IN value to the routine
	 */
	public void setLoginID(java.lang.String value) {
		setValue(org.jooq.examples.sqlserver.adventureworks.humanresources.routines.uspUpdateEmployeeLogin.LoginID, value);
	}

	/**
	 * Set the <code>JobTitle</code> parameter IN value to the routine
	 */
	public void setJobTitle(java.lang.String value) {
		setValue(org.jooq.examples.sqlserver.adventureworks.humanresources.routines.uspUpdateEmployeeLogin.JobTitle, value);
	}

	/**
	 * Set the <code>HireDate</code> parameter IN value to the routine
	 */
	public void setHireDate(java.sql.Timestamp value) {
		setValue(org.jooq.examples.sqlserver.adventureworks.humanresources.routines.uspUpdateEmployeeLogin.HireDate, value);
	}

	/**
	 * Set the <code>CurrentFlag</code> parameter IN value to the routine
	 */
	public void setCurrentFlag(java.lang.Boolean value) {
		setValue(org.jooq.examples.sqlserver.adventureworks.humanresources.routines.uspUpdateEmployeeLogin.CurrentFlag, value);
	}
}
