/**
 * This class is generated by jOOQ
 */
package org.jooq.test.jdbc.generatedclasses.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_2718 extends org.jooq.impl.TableImpl<org.jooq.test.jdbc.generatedclasses.tables.records.T_2718Record> {

	private static final long serialVersionUID = -2082537201;

	/**
	 * The singleton instance of <code>PUBLIC.T_2718</code>
	 */
	public static final org.jooq.test.jdbc.generatedclasses.tables.T_2718 T_2718 = new org.jooq.test.jdbc.generatedclasses.tables.T_2718();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.test.jdbc.generatedclasses.tables.records.T_2718Record> getRecordType() {
		return org.jooq.test.jdbc.generatedclasses.tables.records.T_2718Record.class;
	}

	/**
	 * The column <code>PUBLIC.T_2718.EXCLUDE_ME</code>. 
	 */
	public static final org.jooq.TableField<org.jooq.test.jdbc.generatedclasses.tables.records.T_2718Record, java.lang.Integer> EXCLUDE_ME = createField("EXCLUDE_ME", org.jooq.impl.SQLDataType.INTEGER, T_2718);

	/**
	 * The column <code>PUBLIC.T_2718.XX</code>. 
	 */
	public static final org.jooq.TableField<org.jooq.test.jdbc.generatedclasses.tables.records.T_2718Record, java.lang.Integer> XX = createField("XX", org.jooq.impl.SQLDataType.INTEGER, T_2718);

	/**
	 * No further instances allowed
	 */
	private T_2718() {
		super("T_2718", org.jooq.test.jdbc.generatedclasses.Public.PUBLIC);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.test.jdbc.generatedclasses.tables.records.T_2718Record> getPrimaryKey() {
		return org.jooq.test.jdbc.generatedclasses.Keys.PK_T_2718;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.test.jdbc.generatedclasses.tables.records.T_2718Record>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.test.jdbc.generatedclasses.tables.records.T_2718Record>>asList(org.jooq.test.jdbc.generatedclasses.Keys.PK_T_2718);
	}
}
