/**
 * This class is generated by jOOQ
 */
package org.jooq.util.derby.sys.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public class Sysconglomerates extends org.jooq.impl.TableImpl<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord> {

	private static final long serialVersionUID = 168629972;

	/**
	 * The singleton instance of SYSCONGLOMERATES
	 */
	public static final org.jooq.util.derby.sys.tables.Sysconglomerates SYSCONGLOMERATES = new org.jooq.util.derby.sys.tables.Sysconglomerates();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord> __RECORD_TYPE = org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.String> SCHEMAID = new org.jooq.impl.TableFieldImpl<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.String>("SCHEMAID", org.jooq.impl.SQLDataType.CHAR, SYSCONGLOMERATES);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.String> TABLEID = new org.jooq.impl.TableFieldImpl<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.String>("TABLEID", org.jooq.impl.SQLDataType.CHAR, SYSCONGLOMERATES);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.Long> CONGLOMERATENUMBER = new org.jooq.impl.TableFieldImpl<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.Long>("CONGLOMERATENUMBER", org.jooq.impl.SQLDataType.BIGINT, SYSCONGLOMERATES);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.String> CONGLOMERATENAME = new org.jooq.impl.TableFieldImpl<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.String>("CONGLOMERATENAME", org.jooq.impl.SQLDataType.VARCHAR, SYSCONGLOMERATES);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.Boolean> ISINDEX = new org.jooq.impl.TableFieldImpl<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.Boolean>("ISINDEX", org.jooq.impl.SQLDataType.BOOLEAN, SYSCONGLOMERATES);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.String> DESCRIPTOR = new org.jooq.impl.TableFieldImpl<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.String>("DESCRIPTOR", org.jooq.impl.SQLDataType.CLOB, SYSCONGLOMERATES);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.Boolean> ISCONSTRAINT = new org.jooq.impl.TableFieldImpl<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.Boolean>("ISCONSTRAINT", org.jooq.impl.SQLDataType.BOOLEAN, SYSCONGLOMERATES);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.String> CONGLOMERATEID = new org.jooq.impl.TableFieldImpl<org.jooq.util.derby.sys.tables.records.SysconglomeratesRecord, java.lang.String>("CONGLOMERATEID", org.jooq.impl.SQLDataType.CHAR, SYSCONGLOMERATES);

	/**
	 * No further instances allowed
	 */
	private Sysconglomerates() {
		super("SYSCONGLOMERATES", org.jooq.util.derby.sys.Sys.SYS);
	}
}
